//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace FormRelPadrao.WS_RDCSoap {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_RDCSoap", Namespace="http://tempuri.org/")]
    public partial class WS_RDC : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GravarRDCOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificarVersaoRDCOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadRDCOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadRDC1OperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarRDCOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarRDC1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GravarParamClasseOperationCompleted;
        
        private System.Threading.SendOrPostCallback HomologarRDCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_RDC() {
            this.Url = global::FormRelPadrao.Properties.Settings.Default.FormRelPadrao_WS_RDCSoap_WS_RDC;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GravarRDCCompletedEventHandler GravarRDCCompleted;
        
        /// <remarks/>
        public event VerificarVersaoRDCCompletedEventHandler VerificarVersaoRDCCompleted;
        
        /// <remarks/>
        public event DownloadRDCCompletedEventHandler DownloadRDCCompleted;
        
        /// <remarks/>
        public event DownloadRDC1CompletedEventHandler DownloadRDC1Completed;
        
        /// <remarks/>
        public event BuscarRDCCompletedEventHandler BuscarRDCCompleted;
        
        /// <remarks/>
        public event BuscarRDC1CompletedEventHandler BuscarRDC1Completed;
        
        /// <remarks/>
        public event GravarParamClasseCompletedEventHandler GravarParamClasseCompleted;
        
        /// <remarks/>
        public event HomologarRDCCompletedEventHandler HomologarRDCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GravarRDC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GravarRDC(TRegistro_Cad_RDC Reg_RDC, TRegistro_Cad_ParamClasse[] lReg_ParamClasse) {
            object[] results = this.Invoke("GravarRDC", new object[] {
                        Reg_RDC,
                        lReg_ParamClasse});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GravarRDCAsync(TRegistro_Cad_RDC Reg_RDC, TRegistro_Cad_ParamClasse[] lReg_ParamClasse) {
            this.GravarRDCAsync(Reg_RDC, lReg_ParamClasse, null);
        }
        
        /// <remarks/>
        public void GravarRDCAsync(TRegistro_Cad_RDC Reg_RDC, TRegistro_Cad_ParamClasse[] lReg_ParamClasse, object userState) {
            if ((this.GravarRDCOperationCompleted == null)) {
                this.GravarRDCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGravarRDCOperationCompleted);
            }
            this.InvokeAsync("GravarRDC", new object[] {
                        Reg_RDC,
                        lReg_ParamClasse}, this.GravarRDCOperationCompleted, userState);
        }
        
        private void OnGravarRDCOperationCompleted(object arg) {
            if ((this.GravarRDCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GravarRDCCompleted(this, new GravarRDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificarVersaoRDC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public decimal VerificarVersaoRDC(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC) {
            object[] results = this.Invoke("VerificarVersaoRDC", new object[] {
                        ID_RDC,
                        NM_Classe,
                        Modulo,
                        Ident,
                        ST_RDC});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void VerificarVersaoRDCAsync(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC) {
            this.VerificarVersaoRDCAsync(ID_RDC, NM_Classe, Modulo, Ident, ST_RDC, null);
        }
        
        /// <remarks/>
        public void VerificarVersaoRDCAsync(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC, object userState) {
            if ((this.VerificarVersaoRDCOperationCompleted == null)) {
                this.VerificarVersaoRDCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificarVersaoRDCOperationCompleted);
            }
            this.InvokeAsync("VerificarVersaoRDC", new object[] {
                        ID_RDC,
                        NM_Classe,
                        Modulo,
                        Ident,
                        ST_RDC}, this.VerificarVersaoRDCOperationCompleted, userState);
        }
        
        private void OnVerificarVersaoRDCOperationCompleted(object arg) {
            if ((this.VerificarVersaoRDCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificarVersaoRDCCompleted(this, new VerificarVersaoRDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadRDC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TRegistro_Cad_RDC DownloadRDC(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC) {
            object[] results = this.Invoke("DownloadRDC", new object[] {
                        ID_RDC,
                        NM_Classe,
                        Modulo,
                        Ident,
                        ST_RDC});
            return ((TRegistro_Cad_RDC)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadRDCAsync(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC) {
            this.DownloadRDCAsync(ID_RDC, NM_Classe, Modulo, Ident, ST_RDC, null);
        }
        
        /// <remarks/>
        public void DownloadRDCAsync(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC, object userState) {
            if ((this.DownloadRDCOperationCompleted == null)) {
                this.DownloadRDCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadRDCOperationCompleted);
            }
            this.InvokeAsync("DownloadRDC", new object[] {
                        ID_RDC,
                        NM_Classe,
                        Modulo,
                        Ident,
                        ST_RDC}, this.DownloadRDCOperationCompleted, userState);
        }
        
        private void OnDownloadRDCOperationCompleted(object arg) {
            if ((this.DownloadRDCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadRDCCompleted(this, new DownloadRDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="DownloadRDC1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadRDC2", RequestElementName="DownloadRDC2", RequestNamespace="http://tempuri.org/", ResponseElementName="DownloadRDC2Response", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DownloadRDC2Result")]
        public TRegistro_Cad_RDC DownloadRDC(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC, string Sistema) {
            object[] results = this.Invoke("DownloadRDC1", new object[] {
                        ID_RDC,
                        NM_Classe,
                        Modulo,
                        Ident,
                        ST_RDC,
                        Sistema});
            return ((TRegistro_Cad_RDC)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadRDC1Async(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC, string Sistema) {
            this.DownloadRDC1Async(ID_RDC, NM_Classe, Modulo, Ident, ST_RDC, Sistema, null);
        }
        
        /// <remarks/>
        public void DownloadRDC1Async(string ID_RDC, string NM_Classe, string Modulo, string Ident, string ST_RDC, string Sistema, object userState) {
            if ((this.DownloadRDC1OperationCompleted == null)) {
                this.DownloadRDC1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadRDC1OperationCompleted);
            }
            this.InvokeAsync("DownloadRDC1", new object[] {
                        ID_RDC,
                        NM_Classe,
                        Modulo,
                        Ident,
                        ST_RDC,
                        Sistema}, this.DownloadRDC1OperationCompleted, userState);
        }
        
        private void OnDownloadRDC1OperationCompleted(object arg) {
            if ((this.DownloadRDC1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadRDC1Completed(this, new DownloadRDC1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarRDC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TRegistro_Cad_RDC[] BuscarRDC(string ID_RDC, string DS_RDC, string Modulo, string ST_RDC, string NM_CampoBusca, bool BuscarDTS, bool BuscarRelClasse, bool NaoBuscarRelClasse) {
            object[] results = this.Invoke("BuscarRDC", new object[] {
                        ID_RDC,
                        DS_RDC,
                        Modulo,
                        ST_RDC,
                        NM_CampoBusca,
                        BuscarDTS,
                        BuscarRelClasse,
                        NaoBuscarRelClasse});
            return ((TRegistro_Cad_RDC[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarRDCAsync(string ID_RDC, string DS_RDC, string Modulo, string ST_RDC, string NM_CampoBusca, bool BuscarDTS, bool BuscarRelClasse, bool NaoBuscarRelClasse) {
            this.BuscarRDCAsync(ID_RDC, DS_RDC, Modulo, ST_RDC, NM_CampoBusca, BuscarDTS, BuscarRelClasse, NaoBuscarRelClasse, null);
        }
        
        /// <remarks/>
        public void BuscarRDCAsync(string ID_RDC, string DS_RDC, string Modulo, string ST_RDC, string NM_CampoBusca, bool BuscarDTS, bool BuscarRelClasse, bool NaoBuscarRelClasse, object userState) {
            if ((this.BuscarRDCOperationCompleted == null)) {
                this.BuscarRDCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarRDCOperationCompleted);
            }
            this.InvokeAsync("BuscarRDC", new object[] {
                        ID_RDC,
                        DS_RDC,
                        Modulo,
                        ST_RDC,
                        NM_CampoBusca,
                        BuscarDTS,
                        BuscarRelClasse,
                        NaoBuscarRelClasse}, this.BuscarRDCOperationCompleted, userState);
        }
        
        private void OnBuscarRDCOperationCompleted(object arg) {
            if ((this.BuscarRDCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarRDCCompleted(this, new BuscarRDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="BuscarRDC1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarRDC2", RequestElementName="BuscarRDC2", RequestNamespace="http://tempuri.org/", ResponseElementName="BuscarRDC2Response", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("BuscarRDC2Result")]
        public TRegistro_Cad_RDC[] BuscarRDC(string ID_RDC, string DS_RDC, string Modulo, string ST_RDC, string NM_CampoBusca, bool BuscarDTS, bool BuscarRelClasse, bool NaoBuscarRelClasse, string Sistema) {
            object[] results = this.Invoke("BuscarRDC1", new object[] {
                        ID_RDC,
                        DS_RDC,
                        Modulo,
                        ST_RDC,
                        NM_CampoBusca,
                        BuscarDTS,
                        BuscarRelClasse,
                        NaoBuscarRelClasse,
                        Sistema});
            return ((TRegistro_Cad_RDC[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarRDC1Async(string ID_RDC, string DS_RDC, string Modulo, string ST_RDC, string NM_CampoBusca, bool BuscarDTS, bool BuscarRelClasse, bool NaoBuscarRelClasse, string Sistema) {
            this.BuscarRDC1Async(ID_RDC, DS_RDC, Modulo, ST_RDC, NM_CampoBusca, BuscarDTS, BuscarRelClasse, NaoBuscarRelClasse, Sistema, null);
        }
        
        /// <remarks/>
        public void BuscarRDC1Async(string ID_RDC, string DS_RDC, string Modulo, string ST_RDC, string NM_CampoBusca, bool BuscarDTS, bool BuscarRelClasse, bool NaoBuscarRelClasse, string Sistema, object userState) {
            if ((this.BuscarRDC1OperationCompleted == null)) {
                this.BuscarRDC1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarRDC1OperationCompleted);
            }
            this.InvokeAsync("BuscarRDC1", new object[] {
                        ID_RDC,
                        DS_RDC,
                        Modulo,
                        ST_RDC,
                        NM_CampoBusca,
                        BuscarDTS,
                        BuscarRelClasse,
                        NaoBuscarRelClasse,
                        Sistema}, this.BuscarRDC1OperationCompleted, userState);
        }
        
        private void OnBuscarRDC1OperationCompleted(object arg) {
            if ((this.BuscarRDC1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarRDC1Completed(this, new BuscarRDC1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GravarParamClasse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GravarParamClasse(TRegistro_Cad_ParamClasse[] lReg_ParamClasse) {
            object[] results = this.Invoke("GravarParamClasse", new object[] {
                        lReg_ParamClasse});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GravarParamClasseAsync(TRegistro_Cad_ParamClasse[] lReg_ParamClasse) {
            this.GravarParamClasseAsync(lReg_ParamClasse, null);
        }
        
        /// <remarks/>
        public void GravarParamClasseAsync(TRegistro_Cad_ParamClasse[] lReg_ParamClasse, object userState) {
            if ((this.GravarParamClasseOperationCompleted == null)) {
                this.GravarParamClasseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGravarParamClasseOperationCompleted);
            }
            this.InvokeAsync("GravarParamClasse", new object[] {
                        lReg_ParamClasse}, this.GravarParamClasseOperationCompleted, userState);
        }
        
        private void OnGravarParamClasseOperationCompleted(object arg) {
            if ((this.GravarParamClasseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GravarParamClasseCompleted(this, new GravarParamClasseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HomologarRDC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HomologarRDC(TRegistro_Cad_RDC Reg_RDC) {
            object[] results = this.Invoke("HomologarRDC", new object[] {
                        Reg_RDC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HomologarRDCAsync(TRegistro_Cad_RDC Reg_RDC) {
            this.HomologarRDCAsync(Reg_RDC, null);
        }
        
        /// <remarks/>
        public void HomologarRDCAsync(TRegistro_Cad_RDC Reg_RDC, object userState) {
            if ((this.HomologarRDCOperationCompleted == null)) {
                this.HomologarRDCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHomologarRDCOperationCompleted);
            }
            this.InvokeAsync("HomologarRDC", new object[] {
                        Reg_RDC}, this.HomologarRDCOperationCompleted, userState);
        }
        
        private void OnHomologarRDCOperationCompleted(object arg) {
            if ((this.HomologarRDCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HomologarRDCCompleted(this, new HomologarRDCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TRegistro_Cad_RDC {
        
        private string iD_RDCField;
        
        private string dS_RDCField;
        
        private decimal versaoField;
        
        private string sT_RDCField;
        
        private string moduloField;
        
        private string identField;
        
        private string nM_ClasseField;
        
        private string sistemaField;
        
        private byte[] code_ReportField;
        
        private byte[] code_DataCubeField;
        
        private byte[] code_ChartField;
        
        private TRegistro_Cad_DataSource[] lCad_DataSourceField;
        
        /// <remarks/>
        public string ID_RDC {
            get {
                return this.iD_RDCField;
            }
            set {
                this.iD_RDCField = value;
            }
        }
        
        /// <remarks/>
        public string DS_RDC {
            get {
                return this.dS_RDCField;
            }
            set {
                this.dS_RDCField = value;
            }
        }
        
        /// <remarks/>
        public decimal Versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        public string ST_RDC {
            get {
                return this.sT_RDCField;
            }
            set {
                this.sT_RDCField = value;
            }
        }
        
        /// <remarks/>
        public string Modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
            }
        }
        
        /// <remarks/>
        public string Ident {
            get {
                return this.identField;
            }
            set {
                this.identField = value;
            }
        }
        
        /// <remarks/>
        public string NM_Classe {
            get {
                return this.nM_ClasseField;
            }
            set {
                this.nM_ClasseField = value;
            }
        }
        
        /// <remarks/>
        public string Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Code_Report {
            get {
                return this.code_ReportField;
            }
            set {
                this.code_ReportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Code_DataCube {
            get {
                return this.code_DataCubeField;
            }
            set {
                this.code_DataCubeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Code_Chart {
            get {
                return this.code_ChartField;
            }
            set {
                this.code_ChartField = value;
            }
        }
        
        /// <remarks/>
        public TRegistro_Cad_DataSource[] lCad_DataSource {
            get {
                return this.lCad_DataSourceField;
            }
            set {
                this.lCad_DataSourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TRegistro_Cad_DataSource {
        
        private string iD_DataSourceField;
        
        private string dS_DataSourceField;
        
        private string dS_SQLField;
        
        private System.Nullable<System.DateTime> dT_DataSourceField;
        
        private string dT_DataSourceStringField;
        
        private TRegistro_Cad_ParamClasse[] lCad_ParamClasseField;
        
        /// <remarks/>
        public string ID_DataSource {
            get {
                return this.iD_DataSourceField;
            }
            set {
                this.iD_DataSourceField = value;
            }
        }
        
        /// <remarks/>
        public string DS_DataSource {
            get {
                return this.dS_DataSourceField;
            }
            set {
                this.dS_DataSourceField = value;
            }
        }
        
        /// <remarks/>
        public string DS_SQL {
            get {
                return this.dS_SQLField;
            }
            set {
                this.dS_SQLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DT_DataSource {
            get {
                return this.dT_DataSourceField;
            }
            set {
                this.dT_DataSourceField = value;
            }
        }
        
        /// <remarks/>
        public string DT_DataSourceString {
            get {
                return this.dT_DataSourceStringField;
            }
            set {
                this.dT_DataSourceStringField = value;
            }
        }
        
        /// <remarks/>
        public TRegistro_Cad_ParamClasse[] lCad_ParamClasse {
            get {
                return this.lCad_ParamClasseField;
            }
            set {
                this.lCad_ParamClasseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TRegistro_Cad_ParamClasse {
        
        private string nM_ParamField;
        
        private string nM_CampoFormatField;
        
        private string nM_ClasseField;
        
        private string condicaoBuscaField;
        
        private string codigoCMPField;
        
        private string nomeCMPField;
        
        private string nM_DLLField;
        
        private string tP_DadoField;
        
        private string radioCheckGroupField;
        
        private string st_ObrigatorioField;
        
        private string st_NullField;
        
        /// <remarks/>
        public string NM_Param {
            get {
                return this.nM_ParamField;
            }
            set {
                this.nM_ParamField = value;
            }
        }
        
        /// <remarks/>
        public string NM_CampoFormat {
            get {
                return this.nM_CampoFormatField;
            }
            set {
                this.nM_CampoFormatField = value;
            }
        }
        
        /// <remarks/>
        public string NM_Classe {
            get {
                return this.nM_ClasseField;
            }
            set {
                this.nM_ClasseField = value;
            }
        }
        
        /// <remarks/>
        public string CondicaoBusca {
            get {
                return this.condicaoBuscaField;
            }
            set {
                this.condicaoBuscaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoCMP {
            get {
                return this.codigoCMPField;
            }
            set {
                this.codigoCMPField = value;
            }
        }
        
        /// <remarks/>
        public string NomeCMP {
            get {
                return this.nomeCMPField;
            }
            set {
                this.nomeCMPField = value;
            }
        }
        
        /// <remarks/>
        public string NM_DLL {
            get {
                return this.nM_DLLField;
            }
            set {
                this.nM_DLLField = value;
            }
        }
        
        /// <remarks/>
        public string TP_Dado {
            get {
                return this.tP_DadoField;
            }
            set {
                this.tP_DadoField = value;
            }
        }
        
        /// <remarks/>
        public string RadioCheckGroup {
            get {
                return this.radioCheckGroupField;
            }
            set {
                this.radioCheckGroupField = value;
            }
        }
        
        /// <remarks/>
        public string St_Obrigatorio {
            get {
                return this.st_ObrigatorioField;
            }
            set {
                this.st_ObrigatorioField = value;
            }
        }
        
        /// <remarks/>
        public string St_Null {
            get {
                return this.st_NullField;
            }
            set {
                this.st_NullField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GravarRDCCompletedEventHandler(object sender, GravarRDCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GravarRDCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GravarRDCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void VerificarVersaoRDCCompletedEventHandler(object sender, VerificarVersaoRDCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificarVersaoRDCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificarVersaoRDCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void DownloadRDCCompletedEventHandler(object sender, DownloadRDCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadRDCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadRDCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRegistro_Cad_RDC Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRegistro_Cad_RDC)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void DownloadRDC1CompletedEventHandler(object sender, DownloadRDC1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadRDC1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadRDC1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRegistro_Cad_RDC Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRegistro_Cad_RDC)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void BuscarRDCCompletedEventHandler(object sender, BuscarRDCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarRDCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarRDCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRegistro_Cad_RDC[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRegistro_Cad_RDC[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void BuscarRDC1CompletedEventHandler(object sender, BuscarRDC1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarRDC1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarRDC1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRegistro_Cad_RDC[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRegistro_Cad_RDC[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GravarParamClasseCompletedEventHandler(object sender, GravarParamClasseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GravarParamClasseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GravarParamClasseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void HomologarRDCCompletedEventHandler(object sender, HomologarRDCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HomologarRDCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HomologarRDCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591