//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvNFE {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class SettingsNFE : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsNFE defaultInstance = ((SettingsNFE)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsNFE())));
        
        public static SettingsNFE Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EMPRESA_PADRAO {
            get {
                return ((string)(this["EMPRESA_PADRAO"]));
            }
            set {
                this["EMPRESA_PADRAO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CONFIG_CERTIFICADO {
            get {
                return ((string)(this["CONFIG_CERTIFICADO"]));
            }
            set {
                this["CONFIG_CERTIFICADO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USUARIO_WINDOWS {
            get {
                return ((string)(this["USUARIO_WINDOWS"]));
            }
            set {
                this["USUARIO_WINDOWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SENHA_WINDOWS {
            get {
                return ((string)(this["SENHA_WINDOWS"]));
            }
            set {
                this["SENHA_WINDOWS"] = value;
            }
        }
    }
}
