//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace srvNFE.br.gov.mg.fazenda.hnfe.MGAutorizaLote4 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NFeAutorizacao4SoapBinding", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]
    public partial class NFeAutorizacao4 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NFeAutorizacao4LoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback NFeAutorizacao4LoteZipOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NFeAutorizacao4() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = global::srvNFE.Properties.Settings.Default.srvNFE_br_gov_mg_fazenda_hnfe_MGAutorizaLote4_NFeAutorizacao4;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NFeAutorizacao4LoteCompletedEventHandler NFeAutorizacao4LoteCompleted;
        
        /// <remarks/>
        public event NFeAutorizacao4LoteZipCompletedEventHandler NFeAutorizacao4LoteZipCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/NFeAutorizacao4Lote", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("nfeResultMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("retEnviNFe", IsNullable=false)]
        public object[] NFeAutorizacao4Lote([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")] nfeDadosMsg nfeDadosMsg) {
            object[] results = this.Invoke("NFeAutorizacao4Lote", new object[] {
                        nfeDadosMsg});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void NFeAutorizacao4LoteAsync(nfeDadosMsg nfeDadosMsg) {
            this.NFeAutorizacao4LoteAsync(nfeDadosMsg, null);
        }
        
        /// <remarks/>
        public void NFeAutorizacao4LoteAsync(nfeDadosMsg nfeDadosMsg, object userState) {
            if ((this.NFeAutorizacao4LoteOperationCompleted == null)) {
                this.NFeAutorizacao4LoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNFeAutorizacao4LoteOperationCompleted);
            }
            this.InvokeAsync("NFeAutorizacao4Lote", new object[] {
                        nfeDadosMsg}, this.NFeAutorizacao4LoteOperationCompleted, userState);
        }
        
        private void OnNFeAutorizacao4LoteOperationCompleted(object arg) {
            if ((this.NFeAutorizacao4LoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NFeAutorizacao4LoteCompleted(this, new NFeAutorizacao4LoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/NFeAutorizacao4LoteZip", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("nfeResultMsg", Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("retEnviNFe", IsNullable=false)]
        public object[] NFeAutorizacao4LoteZip([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")] nfeDadosMsgZip nfeDadosMsgZip) {
            object[] results = this.Invoke("NFeAutorizacao4LoteZip", new object[] {
                        nfeDadosMsgZip});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void NFeAutorizacao4LoteZipAsync(nfeDadosMsgZip nfeDadosMsgZip) {
            this.NFeAutorizacao4LoteZipAsync(nfeDadosMsgZip, null);
        }
        
        /// <remarks/>
        public void NFeAutorizacao4LoteZipAsync(nfeDadosMsgZip nfeDadosMsgZip, object userState) {
            if ((this.NFeAutorizacao4LoteZipOperationCompleted == null)) {
                this.NFeAutorizacao4LoteZipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNFeAutorizacao4LoteZipOperationCompleted);
            }
            this.InvokeAsync("NFeAutorizacao4LoteZip", new object[] {
                        nfeDadosMsgZip}, this.NFeAutorizacao4LoteZipOperationCompleted, userState);
        }
        
        private void OnNFeAutorizacao4LoteZipOperationCompleted(object arg) {
            if ((this.NFeAutorizacao4LoteZipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NFeAutorizacao4LoteZipCompleted(this, new NFeAutorizacao4LoteZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]
    public partial class nfeDadosMsg {
        
        private System.Xml.XmlNode[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4")]
    public partial class nfeDadosMsgZip {
        
        private System.Xml.XmlNode[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void NFeAutorizacao4LoteCompletedEventHandler(object sender, NFeAutorizacao4LoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NFeAutorizacao4LoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NFeAutorizacao4LoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void NFeAutorizacao4LoteZipCompletedEventHandler(object sender, NFeAutorizacao4LoteZipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NFeAutorizacao4LoteZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NFeAutorizacao4LoteZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591