//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDFe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_homolog_RecLote_MDFeRecepcao {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_homolog_RecLote_MDFeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeRetRecepcao/MDFeRetRecepcao.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_homolog_RetRec_MDFeRetRecepcao {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_homolog_RetRec_MDFeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeRecepcaoEvento/MDFeRecepcaoEvento." +
            "asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_homolog_RecEvento_MDFeRecepcaoEvento {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_homolog_RecEvento_MDFeRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeConsulta/MDFeConsulta.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_homolog_Consulta_MDFeConsulta {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_homolog_Consulta_MDFeConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.as" +
            "mx")]
        public string MDFe_br_gov_rs_svrs_mdfe_homolog_Status_MDFeStatusServico {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_homolog_Status_MDFeStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeConsNaoEnc/MDFeConsNaoEnc.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_homolog_ConsNaoEnc_MDFeConsNaoEnc {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_homolog_ConsNaoEnc_MDFeConsNaoEnc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.svrs.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_RecLote_MDFeRecepcao {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_RecLote_MDFeRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.svrs.rs.gov.br/ws/MDFeRetRecepcao/MDFeRetRecepcao.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_RetRec_MDFeRetRecepcao {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_RetRec_MDFeRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.svrs.rs.gov.br/ws/MDFeRecepcaoEvento/MDFeRecepcaoEvento.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_RecEvento_MDFeRecepcaoEvento {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_RecEvento_MDFeRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.svrs.rs.gov.br/ws/MDFeConsulta/MDFeConsulta.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_Consulta_MDFeConsulta {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_Consulta_MDFeConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.svrs.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_Status_MDFeStatusServico {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_Status_MDFeStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://mdfe.svrs.rs.gov.br/ws/MDFeConsNaoEnc/MDFeConsNaoEnc.asmx")]
        public string MDFe_br_gov_rs_svrs_mdfe_ConsNaoEnc_MDFeConsNaoEnc {
            get {
                return ((string)(this["MDFe_br_gov_rs_svrs_mdfe_ConsNaoEnc_MDFeConsNaoEnc"]));
            }
        }
    }
}
