//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFCe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3")]
        public string NFCe_br_gov_pr_fazenda_nfce_Autoriza_NfeAutorizacao3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_Autoriza_NfeAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeRetAutorizacao3")]
        public string NFCe_br_gov_pr_fazenda_nfce_RetAutoriza_NfeRetAutorizacao3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_RetAutoriza_NfeRetAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeConsulta3")]
        public string NFCe_br_gov_pr_fazenda_nfce_ConsultaChave_NfeConsulta3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_ConsultaChave_NfeConsulta3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeInutilizacao3")]
        public string NFCe_br_gov_pr_fazenda_nfce_Inutiliza_NfeInutilizacao3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_Inutiliza_NfeInutilizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeStatusServico3")]
        public string NFCe_br_gov_pr_fazenda_nfce_StatusServico_NfeStatusServico3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_StatusServico_NfeStatusServico3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.fazenda.pr.gov.br/nfce/NFeRecepcaoEvento")]
        public string NFCe_br_gov_pr_fazenda_nfce_Evento_RecepcaoEvento {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_Evento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3")]
        public string NFCe_br_gov_pr_fazenda_nfce_homologacao_Autoriza_NfeAutorizacao3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_homologacao_Autoriza_NfeAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeRetAutorizacao3")]
        public string NFCe_br_gov_pr_fazenda_nfce_homologacao_RetAutoriza_NfeRetAutorizacao3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_homologacao_RetAutoriza_NfeRetAutorizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeConsulta3")]
        public string NFCe_br_gov_pr_fazenda_nfce_homologacao_ConsultaChave_NfeConsulta3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_homologacao_ConsultaChave_NfeConsulta3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeInutilizacao3")]
        public string NFCe_br_gov_pr_fazenda_nfce_homologacao_Inutiliza_NfeInutilizacao3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_homologacao_Inutiliza_NfeInutilizacao3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeStatusServico3")]
        public string NFCe_br_gov_pr_fazenda_nfce_homologacao_StatusServico_NfeStatusServico3 {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_homologacao_StatusServico_NfeStatusServico3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeRecepcaoEvento")]
        public string NFCe_br_gov_pr_fazenda_nfce_homologacao_Evento_RecepcaoEvento {
            get {
                return ((string)(this["NFCe_br_gov_pr_fazenda_nfce_homologacao_Evento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://homnfce.sefaz.am.gov.br/nfce-services-nac/services/NfeStatusServico2")]
        public string NFCe_br_gov_am_sefaz_homnfce_StatusServico_NfeStatusServico2 {
            get {
                return ((string)(this["NFCe_br_gov_am_sefaz_homnfce_StatusServico_NfeStatusServico2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeAutorizacao4")]
        public string NFCe_br_gov_pr_sefa_nfce_homologacao_Autoriza4_NFeAutorizacao4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_homologacao_Autoriza4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeRetAutorizacao4")]
        public string NFCe_br_gov_pr_sefa_nfce_homologacao_RetAutorizacao4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_homologacao_RetAutorizacao4_NFeRetAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeConsultaProtocolo4")]
        public string NFCe_br_gov_pr_sefa_nfce_homologacao_ConsultaChave4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_homologacao_ConsultaChave4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeInutilizacao4")]
        public string NFCe_br_gov_pr_sefa_nfce_homologacao_Inutiliza4_NFeInutilizacao4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_homologacao_Inutiliza4_NFeInutilizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeStatusServico4")]
        public string NFCe_br_gov_pr_sefa_nfce_homologacao_StatusServico4_NFeStatusServico4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_homologacao_StatusServico4_NFeStatusServico4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefa.pr.gov.br/nfce/NFeAutorizacao4")]
        public string NFCe_br_gov_pr_sefa_nfce_Autoriza4_NFeAutorizacao4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_Autoriza4_NFeAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefa.pr.gov.br/nfce/NFeRetAutorizacao4")]
        public string NFCe_br_gov_pr_sefa_nfce_RetAutoriza4_NFeRetAutorizacao4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_RetAutoriza4_NFeRetAutorizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefa.pr.gov.br/nfce/NFeConsultaProtocolo4")]
        public string NFCe_br_gov_pr_sefa_nfce_ConsultaChave4_NFeConsultaProtocolo4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_ConsultaChave4_NFeConsultaProtocolo4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefa.pr.gov.br/nfce/NFeInutilizacao4")]
        public string NFCe_br_gov_pr_sefa_nfce_Inutiliza4_NFeInutilizacao4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_Inutiliza4_NFeInutilizacao4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefa.pr.gov.br/nfce/NFeStatusServico4")]
        public string NFCe_br_gov_pr_sefa_nfce_StatusServico4_NFeStatusServico4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_StatusServico4_NFeStatusServico4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfce.sefa.pr.gov.br/nfce/NFeRecepcaoEvento4")]
        public string NFCe_br_gov_pr_sefa_nfce_homologacao_Evento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_homologacao_Evento4_NFeRecepcaoEvento4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfce.sefa.pr.gov.br/nfce/NFeRecepcaoEvento4")]
        public string NFCe_br_gov_pr_sefa_nfce_Evento4_NFeRecepcaoEvento4 {
            get {
                return ((string)(this["NFCe_br_gov_pr_sefa_nfce_Evento4_NFeRecepcaoEvento4"]));
            }
        }
    }
}
