//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.pr.gov.br/cte/CteRecepcao")]
        public string CTe_br_gov_pr_fazenda_cte_Recepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_Recepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.pr.gov.br/cte/CteRetRecepcao")]
        public string CTe_br_gov_pr_fazenda_cte_RetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_RetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.pr.gov.br/cte/CteInutilizacao")]
        public string CTe_br_gov_pr_fazenda_cte_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.pr.gov.br/cte/CteConsulta")]
        public string CTe_br_gov_pr_fazenda_cte_Consulta_CteConsulta {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_Consulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.pr.gov.br/cte/CteStatusServico")]
        public string CTe_br_gov_pr_fazenda_cte_Status_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_Status_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.fazenda.pr.gov.br/cte/CteRecepcao")]
        public string CTe_br_gov_pr_fazenda_cte_homologacao_Recepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_homologacao_Recepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.fazenda.pr.gov.br/cte/CteRetRecepcao")]
        public string CTe_br_gov_pr_fazenda_cte_homologacao_RetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_homologacao_RetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.fazenda.pr.gov.br/cte/CteInutilizacao")]
        public string CTe_br_gov_pr_fazenda_cte_homologacao_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_homologacao_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.fazenda.pr.gov.br/cte/CteConsulta")]
        public string CTe_br_gov_pr_fazenda_cte_homologacao_Consulta_CteConsulta {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_homologacao_Consulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.fazenda.pr.gov.br/cte/CteStatusServico")]
        public string CTe_br_gov_pr_fazenda_cte_homologacao_Status_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_homologacao_Status_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.pr.gov.br/cte/CteRecepcaoEvento")]
        public string CTe_br_gov_pr_fazenda_cte_Evento_CteRecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_Evento_CteRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.fazenda.pr.gov.br/cte/CteRecepcaoEvento")]
        public string CTe_br_gov_pr_fazenda_cte_homologacao_Evento_CteRecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_pr_fazenda_cte_homologacao_Evento_CteRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/CteRecepcao.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_SVCRecepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_SVCRecepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/CteRetRecepcao.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_SVCRetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_SVCRetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/CteStatusServico.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_SVCStatusServico_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_SVCStatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.mt.gov.br/ctews/services/CteRecepcao")]
        public string CTe_br_gov_mt_sefaz_cte_Recepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_mt_sefaz_cte_Recepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.mt.gov.br/ctews/services/CteRetRecepcao")]
        public string CTe_br_gov_mt_sefaz_cte_RetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_mt_sefaz_cte_RetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.mt.gov.br/ctews/services/CteInutilizacao")]
        public string CTe_br_gov_mt_sefaz_cte_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_mt_sefaz_cte_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.mt.gov.br/ctews/services/CteConsulta")]
        public string CTe_br_gov_mt_sefaz_cte_Consulta_CteConsulta {
            get {
                return ((string)(this["CTe_br_gov_mt_sefaz_cte_Consulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.mt.gov.br/ctews/services/CteStatusServico")]
        public string CTe_br_gov_mt_sefaz_cte_StatusServico_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_mt_sefaz_cte_StatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.mt.gov.br/ctews2/services/CteRecepcaoEvento")]
        public string CTe_br_gov_mt_sefaz_cte_Evento_CteRecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_mt_sefaz_cte_Evento_CteRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://producao.cte.ms.gov.br/cteWEB/CteRecepcao.asmx")]
        public string CTe_br_gov_ms_cte_producao_Recepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_ms_cte_producao_Recepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://producao.cte.ms.gov.br/cteWEB/CteRetRecepcao.asmx")]
        public string CTe_br_gov_ms_cte_producao_RetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_ms_cte_producao_RetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://producao.cte.ms.gov.br/cteWEB/CteInutilizacao.asmx")]
        public string CTe_br_gov_ms_cte_producao_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_ms_cte_producao_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://producao.cte.ms.gov.br/cteWEB/CteConsulta.asmx")]
        public string CTe_br_gov_ms_cte_producao_Consulta_CteConsulta {
            get {
                return ((string)(this["CTe_br_gov_ms_cte_producao_Consulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://producao.cte.ms.gov.br/cteWEB/CteStatusServico.asmx")]
        public string CTe_br_gov_ms_cte_producao_StatusServico_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_ms_cte_producao_StatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://producao.cte.ms.gov.br/cteWEB/CteRecepcaoEvento.asmx")]
        public string CTe_br_gov_ms_cte_producao_Evento_CteRecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_ms_cte_producao_Evento_CteRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.mg.gov.br/cte/services/CteRecepcao")]
        public string CTe_br_gov_mg_fazenda_cte_Recepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_mg_fazenda_cte_Recepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.mg.gov.br/cte/services/CteRetRecepcao")]
        public string CTe_br_gov_mg_fazenda_cte_RetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_mg_fazenda_cte_RetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.mg.gov.br/cte/services/CteInutilizacao")]
        public string CTe_br_gov_mg_fazenda_cte_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_mg_fazenda_cte_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.mg.gov.br/cte/services/CteConsulta")]
        public string CTe_br_gov_mg_fazenda_cte_Consulta_CteConsulta {
            get {
                return ((string)(this["CTe_br_gov_mg_fazenda_cte_Consulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.mg.gov.br/cte/services/CteStatusServico")]
        public string CTe_br_gov_mg_fazenda_cte_StatusServico_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_mg_fazenda_cte_StatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.fazenda.mg.gov.br/cte/services/RecepcaoEvento")]
        public string CTe_br_gov_mg_fazenda_cte_Evento_RecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_mg_fazenda_cte_Evento_RecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.rs.gov.br/ws/cterecepcao/CteRecepcao.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_Recepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_Recepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.rs.gov.br/ws/cteretrecepcao/CteRetRecepcao.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_RetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_RetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.rs.gov.br/ws/cteinutilizacao/cteinutilizacao.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.rs.gov.br/ws/cteconsulta/cteconsulta.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_Consulta_CteConsulta {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_Consulta_CteConsulta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.rs.gov.br/ws/ctestatusservico/ctestatusservico.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_StatusServico_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_StatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cte.sefaz.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_Evento_CteRecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_Evento_CteRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteWEB/services/cteInutilizacao.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nfe.fazenda.sp.gov.br/cteweb/services/cteRecepcaoEvento.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_Evento_CteRecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_Evento_CteRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcao.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_homologacao_Recepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_homologacao_Recepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteRetRecepcao.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_homologacao_RetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_homologacao_RetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteInutilizacao.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_homologacao_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_homologacao_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteStatusServico.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_homologacao_StatusServico_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_homologacao_StatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.nfe.fazenda.sp.gov.br/cteweb/services/cteRecepcaoEvento.asmx")]
        public string CTe_br_gov_sp_fazenda_nfe_homologacao_Evento_CteRecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_sp_fazenda_nfe_homologacao_Evento_CteRecepcaoEvento"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.sefaz.rs.gov.br/ws/cterecepcao/CteRecepcao.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_homologacao_Recepcao_CteRecepcao {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_homologacao_Recepcao_CteRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.sefaz.rs.gov.br/ws/cteretrecepcao/CteRetRecepcao.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_homologacao_RetRecepcao_CteRetRecepcao {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_homologacao_RetRecepcao_CteRetRecepcao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.sefaz.rs.gov.br/ws/cteinutilizacao/cteinutilizacao.asmx")]
        public string CTe_br_gov_rs_sefaz_cte_homologacao_Inutilizacao_CteInutilizacao {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_homologacao_Inutilizacao_CteInutilizacao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.sefaz.rs.gov.br/ws/ctestatusservico/ctestatusservico.asmx" +
            "")]
        public string CTe_br_gov_rs_sefaz_cte_homologacao_StatusServico_CteStatusServico {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_homologacao_StatusServico_CteStatusServico"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://homologacao.cte.sefaz.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.as" +
            "mx")]
        public string CTe_br_gov_rs_sefaz_cte_homologacao_Evento_CteRecepcaoEvento {
            get {
                return ((string)(this["CTe_br_gov_rs_sefaz_cte_homologacao_Evento_CteRecepcaoEvento"]));
            }
        }
    }
}
