//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesUtils {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesUtils() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utils.ResourcesUtils", typeof(ResourcesUtils).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ;----------------------------------------------------------------------------;
        ///;                                                                            ;
        ///;  BEMAFI32.INI                                                              ;
        ///;  Ver 5.10.6.5 - Janeiro/2010                                                 ;
        ///;                                                                            ;
        ///;  Arquivo de inicializacao da dll BemaFI32 para as impressoras fiscais      ;
        ///;  MP-20 FI II, MP-40 FI II, M [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string BemaFi32 {
            get {
                return ResourceManager.GetString("BemaFi32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ;----------------------------------------------------------------------------;
        ///;                                                                            ;
        ///;  BEMAFI64.INI                                                              ;
        ///;  Ver 6.1.0.0 - Fevereiro/2011                                              ;
        ///;                                                                            ;
        ///;  Arquivo de inicializacao da dll BemaFI64 para as impressoras fiscais      ;
        ///;  MP-20 FI II, MP-40 FI II, MP- [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string BemaFi64 {
            get {
                return ResourceManager.GetString("BemaFi64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [Sistema] 
        ///ModeloImp=ELGIN_FIT
        ///Porta=COM1 
        ///Path=C:\ 
        ///HabilitaICMSCupom=1 
        ///DINHEIRO=0 
        ///EspacamentoDocumentos=7 
        ///SANGRIA=1 
        ///SUPRIMENTO=0 
        ///HOMOLOGAR=1 
        ///BAUD=115200 
        ///HabilitaCorte=1 
        ///Gera_RFD_REDZ=1 
        ///TimeOutRedZ=40 
        ///Endereco=278 
        ///PathRFD=C:\RFD 
        ///TimeOutComandos=10 
        ///ChecaCTS=0 
        ///CorrigeRelogioZ=0 
        ///LMFAutomatico=1 
        ///[Flags] 
        ///NumPkt=43 
        ///CupomManiaLido=0
        ///CupomManiaValorAux=0
        ///CupomManiaTotalImp=0,00.
        /// </summary>
        public static string elgin {
            get {
                return ResourceManager.GetString("elgin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo_tecnoaliance {
            get {
                object obj = ResourceManager.GetObject("logo_tecnoaliance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;&lt;root type=&quot;PerpetuumSoft.Reporting.DOM.Document&quot; id=&quot;1&quot; version=&quot;2&quot; GridStep=&quot;59.055118110236222&quot; IsTemplate=&quot;true&quot; CommonScript=&quot;private string FormatValorAsterisco(string valor, int casas)&amp;#xD;&amp;#xA;{&amp;#xD;&amp;#xA;  string format = &amp;quot;#&amp;quot;;&amp;#xD;&amp;#xA;            &amp;#xD;&amp;#xA;  int totalMeio = Convert.ToInt32(Math.Round(Convert.ToDecimal(((casas - (valor.ToString().Length+3)) / 2)), 0));&amp;#xD;&amp;#xA;&amp;#xD;&amp;#xA;  for (int i = 0; i &amp;lt; (casas - 2); i++)&amp;#xD;&amp; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string ModeloCheque {
            get {
                return ResourceManager.GetString("ModeloCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;&lt;root type=&quot;PerpetuumSoft.Instrumentation.Model.Instrument&quot; id=&quot;1&quot; version=&quot;2&quot; Size=&quot;468.75;640.625&quot; GridStep=&quot;50&quot; Focused=&quot;true&quot; SnapToGrid=&quot;false&quot; Name=&quot;Instrument&quot; MeasureUnit=&quot;Pixel&quot;&gt;&lt;Parameters type=&quot;PerpetuumSoft.Instrumentation.Model.ParameterCollection&quot; id=&quot;2&quot; /&gt;&lt;Expressions type=&quot;PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection&quot; id=&quot;3&quot; /&gt;&lt;Elements type=&quot;PerpetuumSoft.Instrumentation.Model.ElementCollection&quot; id=&quot;4&quot;&gt;&lt;Item type=&quot;Per [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Portador {
            get {
                return ResourceManager.GetString("Portador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;&lt;root type=&quot;PerpetuumSoft.Instrumentation.Model.Instrument&quot; id=&quot;1&quot; version=&quot;2&quot; Size=&quot;468.75;931.25&quot; GridStep=&quot;50&quot; Focused=&quot;true&quot; SnapToGrid=&quot;false&quot; Name=&quot;Instrument&quot; MeasureUnit=&quot;Pixel&quot;&gt;&lt;Parameters type=&quot;PerpetuumSoft.Instrumentation.Model.ParameterCollection&quot; id=&quot;2&quot; /&gt;&lt;Expressions type=&quot;PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection&quot; id=&quot;3&quot; /&gt;&lt;Elements type=&quot;PerpetuumSoft.Instrumentation.Model.ElementCollection&quot; id=&quot;4&quot;&gt;&lt;Item type=&quot;Perp [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string Tanque {
            get {
                return ResourceManager.GetString("Tanque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        /// </summary>
        public static System.Drawing.Icon TecnoAliance_ICO {
            get {
                object obj = ResourceManager.GetObject("TecnoAliance_ICO", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;&lt;root type=&quot;PerpetuumSoft.Instrumentation.Model.Instrument&quot; id=&quot;1&quot; version=&quot;2&quot; Size=&quot;468.75;640.625&quot; GridStep=&quot;50&quot; Focused=&quot;true&quot; SnapToGrid=&quot;false&quot; Name=&quot;Instrument&quot; MeasureUnit=&quot;Pixel&quot;&gt;&lt;Parameters type=&quot;PerpetuumSoft.Instrumentation.Model.ParameterCollection&quot; id=&quot;2&quot; /&gt;&lt;Expressions type=&quot;PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection&quot; id=&quot;3&quot; /&gt;&lt;Elements type=&quot;PerpetuumSoft.Instrumentation.Model.ElementCollection&quot; id=&quot;4&quot;&gt;&lt;Item type=&quot;Per [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string VendasDia {
            get {
                return ResourceManager.GetString("VendasDia", resourceCulture);
            }
        }
    }
}
