//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class SettingsUtils : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsUtils defaultInstance = ((SettingsUtils)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsUtils())));
        
        public static SettingsUtils Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169, 212, 121")]
        public global::System.Drawing.Color COLOR_1 {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_1"]));
            }
            set {
                this["COLOR_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125, 199, 212")]
        public global::System.Drawing.Color COLOR_2 {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_2"]));
            }
            set {
                this["COLOR_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("183, 182, 181")]
        public global::System.Drawing.Color COLOR_3 {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_3"]));
            }
            set {
                this["COLOR_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<iframe style=\"WIDTH: 170px; HEIGHT: 56px\"\r\nsrc=\"http://tecnoaliance.mysuite1.com" +
            ".br/empresas/tna/verifica.php\"\r\nframeborder=0 scrolling=no>\r\n</iframe>")]
        public string URL_SUPORTE {
            get {
                return ((string)(this["URL_SUPORTE"]));
            }
            set {
                this["URL_SUPORTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\" standalone=\"yes\"?><root type=\"PerpetuumSoft" +
            ".Instrumentation.Model.Instrument\" id=\"1\" version=\"2\" Size=\"587.5;1543.75\" GridS" +
            "tep=\"50\" SnapToGrid=\"false\" Name=\"Instrument\" MeasureUnit=\"Pixel\"><Parameters ty" +
            "pe=\"PerpetuumSoft.Instrumentation.Model.ParameterCollection\" id=\"2\" /><Expressio" +
            "ns type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"3\"" +
            " /><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"4\"" +
            "><Item type=\"PerpetuumSoft.Instrumentation.Model.RoundedRectangle\" id=\"5\" Name=\"" +
            "RoundedRectangle1\" Size=\"500;1500\" Style=\"Default\" Center=\"290.625;778.125\"><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"6\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"7\" Widt" +
            "h=\"9\" Color=\"148, 148, 148\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidF" +
            "ill\" id=\"8\" Color=\"229, 229, 229\" /></Item><Item type=\"PerpetuumSoft.Instrumenta" +
            "tion.Model.Rectangle\" id=\"9\" Name=\"Rectangle1\" Size=\"62.5;1356.25\" Style=\"Defaul" +
            "t\" Center=\"190.625;778.125\"><Expressions type=\"PerpetuumSoft.Instrumentation.Mod" +
            "el.ExpressionBindingCollection\" id=\"10\" /><Stroke type=\"PerpetuumSoft.Framework." +
            "Drawing.SimpleStroke\" id=\"11\" Width=\"10\" Color=\"132, 132, 132\" /><Fill type=\"Per" +
            "petuumSoft.Framework.Drawing.SolidFill\" id=\"12\" Color=\"123, 123, 123\" /></Item><" +
            "Item type=\"PerpetuumSoft.Instrumentation.Model.Guide\" id=\"13\" StartPoint=\"190.62" +
            "5;1428.125\" Name=\"Guide1\" EndPoint=\"190.625;128.125\"><Expressions type=\"Perpetuu" +
            "mSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"14\" /><Elements typ" +
            "e=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"15\"><Item type=\"Pe" +
            "rpetuumSoft.Instrumentation.Model.Scale\" id=\"16\" Name=\"Scale1\"><Expressions type" +
            "=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"17\" /><El" +
            "ements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"18\"><Ite" +
            "m type=\"PerpetuumSoft.Instrumentation.Model.Slider\" id=\"19\" Value=\"69.2307692307" +
            "69226\" Name=\"Slider1\"><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Exp" +
            "ressionBindingCollection\" id=\"20\" /><Elements type=\"PerpetuumSoft.Instrumentatio" +
            "n.Model.ElementCollection\" id=\"21\"><Item type=\"PerpetuumSoft.Instrumentation.Mod" +
            "el.LinearLevel\" id=\"22\" Distance=\"5.6843418860808015E-14\" Width=\"62.5\" Name=\"Lin" +
            "earLevel1\" Style=\"Default\" Value=\"69.2307692307692\" StartCap=\"Flat\" MinLimit=\"-2" +
            "\" EndCap=\"Flat\" Effect3D=\"Flat\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Si" +
            "mpleStroke\" id=\"23\" Width=\"10\" Color=\"132, 132, 132\" /><Expressions type=\"Perpet" +
            "uumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"24\"><Item type=\"P" +
            "erpetuumSoft.Instrumentation.Model.ExpressionBinding\" id=\"25\" Expression=\"Slider" +
            "1.Value\" PropertyName=\"Value\" /></Expressions><Fill type=\"PerpetuumSoft.Framewor" +
            "k.Drawing.SolidFill\" id=\"26\" Color=\"153, 205, 255\" /><Colors type=\"PerpetuumSoft" +
            ".Instrumentation.Model.Drawing.ColorSectionCollection\" id=\"27\" /></Item><Item ty" +
            "pe=\"PerpetuumSoft.Instrumentation.Model.Rectangle\" id=\"28\" Name=\"Rectangle2\" Siz" +
            "e=\"131.25;59.375\" Style=\"Default\" Center=\"190.62499999999983;528.125\"><Expressio" +
            "ns type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"29" +
            "\"><Item type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBinding\" id=\"30\" Exp" +
            "ression=\"r(0)\" PropertyName=\"Center\" /></Expressions><Stroke type=\"PerpetuumSoft" +
            ".Framework.Drawing.SimpleStroke\" id=\"31\" Width=\"10\" Color=\"148, 148, 148\" /><Fil" +
            "l type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"32\" Color=\"229, 229, 229\"" +
            " /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.Label\" id=\"33\" Text=\"6" +
            "9.2\" Size=\"131.25;59.375\" Style=\"Default\" Center=\"190.62499999999983;533.125\" Na" +
            "me=\"Label1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"34\" " +
            "FamilyName=\"Microsoft Sans Serif\" Size=\"11.25\" Underline=\"Off\" Strikeout=\"Off\" I" +
            "talic=\"Off\" Bold=\"On\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.E" +
            "xpressionBindingCollection\" id=\"35\"><Item type=\"PerpetuumSoft.Instrumentation.Mo" +
            "del.ExpressionBinding\" id=\"36\" Expression=\"format(Slider1.Value,&quot;0.0&quot;)" +
            "\" PropertyName=\"Text\" /><Item type=\"PerpetuumSoft.Instrumentation.Model.Expressi" +
            "onBinding\" id=\"37\" Expression=\"r(0) + [0,5]\" PropertyName=\"Center\" /></Expressio" +
            "ns><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"38\" Color=\"DimGray" +
            "\" /></Item></Elements></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.Tic" +
            "ks\" id=\"39\" Distance=\"62.5\" Style=\"Default\" Name=\"Ticks1\" Length=\"62.5\" SubDivis" +
            "ions=\"5\" SubLength=\"46.875\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Simple" +
            "Stroke\" id=\"40\" Width=\"5\" Style=\"None\" /><Colorizer type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.Drawing.SingleColorColorizer\" id=\"41\" Color=\"148, 148, 148\" /><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"42\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.ScaleLabels\" id" +
            "=\"43\" OddLabelsDistance=\"0\" Distance=\"184.375\" Style=\"Default\" Name=\"ScaleLabels" +
            "1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"44\" FamilyNam" +
            "e=\"Microsoft Sans Serif\" Size=\"12\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" " +
            "Bold=\"On\" /><Format type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"45\" UseCu" +
            "ltureSettings=\"true\" UseGroupSeparator=\"true\" /><Expressions type=\"PerpetuumSoft" +
            ".Instrumentation.Model.ExpressionBindingCollection\" id=\"46\" /></Item></Elements>" +
            "</Item></Elements></Item></Elements><Styles type=\"PerpetuumSoft.Instrumentation." +
            "Styles.StyleCollection\" id=\"47\"><Item type=\"PerpetuumSoft.Instrumentation.Styles" +
            ".Style\" id=\"48\" Name=\"Default\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Sim" +
            "pleStroke\" id=\"49\" Width=\"1\" Style=\"None\" /><Font type=\"PerpetuumSoft.Framework." +
            "Drawing.FontDescriptor\" id=\"50\" FamilyName=\"Microsoft Sans Serif\" /></Item></Sty" +
            "les></root>")]
        public string Tanque {
            get {
                return ((string)(this["Tanque"]));
            }
            set {
                this["Tanque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Instrumentation.Model.Instrument\" id=\"1\" version=\"2\" Size=\"490.625;125\" GridStep" +
            "=\"50\" Focused=\"true\" SnapToGrid=\"false\" Name=\"Instrument\" MeasureUnit=\"Pixel\"><P" +
            "arameters type=\"PerpetuumSoft.Instrumentation.Model.ParameterCollection\" id=\"2\" " +
            "/><Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollec" +
            "tion\" id=\"3\" /><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollec" +
            "tion\" id=\"4\"><Item type=\"PerpetuumSoft.Instrumentation.Model.Specialized.Odomete" +
            "r\" id=\"5\" Value=\"123\" Center=\"228.125;59.375\" Name=\"odometro\" Size=\"487.5;87.5\">" +
            "<Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"6\" Width=\"1\" /><" +
            "ForeFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"7\" Color=\"Black\" /" +
            "><FirstDigitBackFill type=\"PerpetuumSoft.Framework.Drawing.MultiGradientFill\" id" +
            "=\"8\" Angle=\"90\"><Colors type=\"PerpetuumSoft.Framework.Drawing.GradientColorColle" +
            "ction\" id=\"9\"><Item type=\"PerpetuumSoft.Framework.Drawing.GradientColor\" id=\"10\"" +
            " Portion=\"0\" Color=\"Red\" /><Item type=\"PerpetuumSoft.Framework.Drawing.GradientC" +
            "olor\" id=\"11\" Portion=\"0.5\" Color=\"255, 255, 192\" /><Item type=\"PerpetuumSoft.Fr" +
            "amework.Drawing.GradientColor\" id=\"12\" Portion=\"1\" Color=\"Red\" /></Colors></Firs" +
            "tDigitBackFill><FirstDigitForeFill type=\"PerpetuumSoft.Framework.Drawing.SolidFi" +
            "ll\" id=\"13\" Color=\"Blue\" /><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescr" +
            "iptor\" id=\"14\" FamilyName=\"Arial\" Size=\"20\" /><Expressions type=\"PerpetuumSoft.I" +
            "nstrumentation.Model.ExpressionBindingCollection\" id=\"15\" /><BackFill type=\"Perp" +
            "etuumSoft.Framework.Drawing.MultiGradientFill\" id=\"16\" Angle=\"90\"><Colors type=\"" +
            "PerpetuumSoft.Framework.Drawing.GradientColorCollection\" id=\"17\"><Item type=\"Per" +
            "petuumSoft.Framework.Drawing.GradientColor\" id=\"18\" Portion=\"0\" Color=\"32, 32, 3" +
            "2\" /><Item type=\"PerpetuumSoft.Framework.Drawing.GradientColor\" id=\"19\" Portion=" +
            "\"0.5\" Color=\"White\" /><Item type=\"PerpetuumSoft.Framework.Drawing.GradientColor\"" +
            " id=\"20\" Portion=\"1\" Color=\"32, 32, 32\" /></Colors></BackFill></Item></Elements>" +
            "<Styles type=\"PerpetuumSoft.Instrumentation.Styles.StyleCollection\" id=\"21\"><Ite" +
            "m type=\"PerpetuumSoft.Instrumentation.Styles.Style\" id=\"22\" Name=\"Default\"><Stro" +
            "ke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"23\" Width=\"1\" /><Font" +
            " type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"24\" FamilyName=\"Micro" +
            "soft Sans Serif\" /></Item></Styles></root>")]
        public string Hodometro {
            get {
                return ((string)(this["Hodometro"]));
            }
            set {
                this["Hodometro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\" standalone=\"yes\"?><root type=\"PerpetuumSoft" +
            ".Instrumentation.Model.Instrument\" id=\"1\" version=\"2\" Size=\"587.5;1543.75\" GridS" +
            "tep=\"50\" SnapToGrid=\"false\" Name=\"Instrument\" MeasureUnit=\"Pixel\"><Parameters ty" +
            "pe=\"PerpetuumSoft.Instrumentation.Model.ParameterCollection\" id=\"2\" /><Expressio" +
            "ns type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"3\"" +
            " /><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"4\"" +
            "><Item type=\"PerpetuumSoft.Instrumentation.Model.RoundedRectangle\" id=\"5\" Name=\"" +
            "RoundedRectangle1\" Size=\"500;1500\" Style=\"Default\" Center=\"290.625;778.125\"><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"6\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"7\" Widt" +
            "h=\"9\" Color=\"148, 148, 148\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidF" +
            "ill\" id=\"8\" Color=\"229, 229, 229\" /></Item><Item type=\"PerpetuumSoft.Instrumenta" +
            "tion.Model.Rectangle\" id=\"9\" Name=\"Rectangle1\" Size=\"62.5;1356.25\" Style=\"Defaul" +
            "t\" Center=\"190.625;778.125\"><Expressions type=\"PerpetuumSoft.Instrumentation.Mod" +
            "el.ExpressionBindingCollection\" id=\"10\" /><Stroke type=\"PerpetuumSoft.Framework." +
            "Drawing.SimpleStroke\" id=\"11\" Width=\"10\" Color=\"132, 132, 132\" /><Fill type=\"Per" +
            "petuumSoft.Framework.Drawing.SolidFill\" id=\"12\" Color=\"123, 123, 123\" /></Item><" +
            "Item type=\"PerpetuumSoft.Instrumentation.Model.Guide\" id=\"13\" StartPoint=\"190.62" +
            "5;1428.125\" Name=\"Guide1\" EndPoint=\"190.625;128.125\"><Expressions type=\"Perpetuu" +
            "mSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"14\" /><Elements typ" +
            "e=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"15\"><Item type=\"Pe" +
            "rpetuumSoft.Instrumentation.Model.Scale\" id=\"16\" Name=\"Scale1\"><Expressions type" +
            "=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"17\" /><El" +
            "ements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"18\"><Ite" +
            "m type=\"PerpetuumSoft.Instrumentation.Model.Slider\" id=\"19\" Value=\"69.2307692307" +
            "69226\" Name=\"Slider1\"><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Exp" +
            "ressionBindingCollection\" id=\"20\" /><Elements type=\"PerpetuumSoft.Instrumentatio" +
            "n.Model.ElementCollection\" id=\"21\"><Item type=\"PerpetuumSoft.Instrumentation.Mod" +
            "el.LinearLevel\" id=\"22\" Distance=\"5.6843418860808015E-14\" Width=\"62.5\" Name=\"Lin" +
            "earLevel1\" Style=\"Default\" Value=\"69.2307692307692\" StartCap=\"Flat\" MinLimit=\"-2" +
            "\" EndCap=\"Flat\" Effect3D=\"Flat\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Si" +
            "mpleStroke\" id=\"23\" Width=\"10\" Color=\"132, 132, 132\" /><Expressions type=\"Perpet" +
            "uumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"24\"><Item type=\"P" +
            "erpetuumSoft.Instrumentation.Model.ExpressionBinding\" id=\"25\" Expression=\"Slider" +
            "1.Value\" PropertyName=\"Value\" /></Expressions><Fill type=\"PerpetuumSoft.Framewor" +
            "k.Drawing.SolidFill\" id=\"26\" Color=\"153, 205, 255\" /><Colors type=\"PerpetuumSoft" +
            ".Instrumentation.Model.Drawing.ColorSectionCollection\" id=\"27\" /></Item><Item ty" +
            "pe=\"PerpetuumSoft.Instrumentation.Model.Rectangle\" id=\"28\" Name=\"Rectangle2\" Siz" +
            "e=\"131.25;59.375\" Style=\"Default\" Center=\"190.62499999999983;528.125\"><Expressio" +
            "ns type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"29" +
            "\"><Item type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBinding\" id=\"30\" Exp" +
            "ression=\"r(0)\" PropertyName=\"Center\" /></Expressions><Stroke type=\"PerpetuumSoft" +
            ".Framework.Drawing.SimpleStroke\" id=\"31\" Width=\"10\" Color=\"148, 148, 148\" /><Fil" +
            "l type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"32\" Color=\"229, 229, 229\"" +
            " /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.Label\" id=\"33\" Text=\"6" +
            "9.2\" Size=\"131.25;59.375\" Style=\"Default\" Center=\"190.62499999999983;533.125\" Na" +
            "me=\"Label1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"34\" " +
            "FamilyName=\"Microsoft Sans Serif\" Size=\"11.25\" Underline=\"Off\" Strikeout=\"Off\" I" +
            "talic=\"Off\" Bold=\"On\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.E" +
            "xpressionBindingCollection\" id=\"35\"><Item type=\"PerpetuumSoft.Instrumentation.Mo" +
            "del.ExpressionBinding\" id=\"36\" Expression=\"format(Slider1.Value,&quot;0.0&quot;)" +
            "\" PropertyName=\"Text\" /><Item type=\"PerpetuumSoft.Instrumentation.Model.Expressi" +
            "onBinding\" id=\"37\" Expression=\"r(0) + [0,5]\" PropertyName=\"Center\" /></Expressio" +
            "ns><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"38\" Color=\"DimGray" +
            "\" /></Item></Elements></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.Tic" +
            "ks\" id=\"39\" Distance=\"62.5\" Style=\"Default\" Name=\"Ticks1\" Length=\"62.5\" SubDivis" +
            "ions=\"5\" SubLength=\"46.875\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Simple" +
            "Stroke\" id=\"40\" Width=\"5\" Style=\"None\" /><Colorizer type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.Drawing.SingleColorColorizer\" id=\"41\" Color=\"148, 148, 148\" /><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"42\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.ScaleLabels\" id" +
            "=\"43\" OddLabelsDistance=\"0\" Distance=\"184.375\" Style=\"Default\" Name=\"ScaleLabels" +
            "1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"44\" FamilyNam" +
            "e=\"Microsoft Sans Serif\" Size=\"12\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" " +
            "Bold=\"On\" /><Format type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"45\" UseCu" +
            "ltureSettings=\"true\" UseGroupSeparator=\"true\" /><Expressions type=\"PerpetuumSoft" +
            ".Instrumentation.Model.ExpressionBindingCollection\" id=\"46\" /></Item></Elements>" +
            "</Item></Elements></Item></Elements><Styles type=\"PerpetuumSoft.Instrumentation." +
            "Styles.StyleCollection\" id=\"47\"><Item type=\"PerpetuumSoft.Instrumentation.Styles" +
            ".Style\" id=\"48\" Name=\"Default\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Sim" +
            "pleStroke\" id=\"49\" Width=\"1\" Style=\"None\" /><Font type=\"PerpetuumSoft.Framework." +
            "Drawing.FontDescriptor\" id=\"50\" FamilyName=\"Microsoft Sans Serif\" /></Item></Sty" +
            "les></root>")]
        public string VendasDia {
            get {
                return ((string)(this["VendasDia"]));
            }
            set {
                this["VendasDia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\" standalone=\"yes\"?><root type=\"PerpetuumSoft" +
            ".Instrumentation.Model.Instrument\" id=\"1\" version=\"2\" Size=\"587.5;1543.75\" GridS" +
            "tep=\"50\" SnapToGrid=\"false\" Name=\"Instrument\" MeasureUnit=\"Pixel\"><Parameters ty" +
            "pe=\"PerpetuumSoft.Instrumentation.Model.ParameterCollection\" id=\"2\" /><Expressio" +
            "ns type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"3\"" +
            " /><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"4\"" +
            "><Item type=\"PerpetuumSoft.Instrumentation.Model.RoundedRectangle\" id=\"5\" Name=\"" +
            "RoundedRectangle1\" Size=\"500;1500\" Style=\"Default\" Center=\"290.625;778.125\"><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"6\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"7\" Widt" +
            "h=\"9\" Color=\"148, 148, 148\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidF" +
            "ill\" id=\"8\" Color=\"229, 229, 229\" /></Item><Item type=\"PerpetuumSoft.Instrumenta" +
            "tion.Model.Rectangle\" id=\"9\" Name=\"Rectangle1\" Size=\"62.5;1356.25\" Style=\"Defaul" +
            "t\" Center=\"190.625;778.125\"><Expressions type=\"PerpetuumSoft.Instrumentation.Mod" +
            "el.ExpressionBindingCollection\" id=\"10\" /><Stroke type=\"PerpetuumSoft.Framework." +
            "Drawing.SimpleStroke\" id=\"11\" Width=\"10\" Color=\"132, 132, 132\" /><Fill type=\"Per" +
            "petuumSoft.Framework.Drawing.SolidFill\" id=\"12\" Color=\"123, 123, 123\" /></Item><" +
            "Item type=\"PerpetuumSoft.Instrumentation.Model.Guide\" id=\"13\" StartPoint=\"190.62" +
            "5;1428.125\" Name=\"Guide1\" EndPoint=\"190.625;128.125\"><Expressions type=\"Perpetuu" +
            "mSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"14\" /><Elements typ" +
            "e=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"15\"><Item type=\"Pe" +
            "rpetuumSoft.Instrumentation.Model.Scale\" id=\"16\" Name=\"Scale1\"><Expressions type" +
            "=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"17\" /><El" +
            "ements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"18\"><Ite" +
            "m type=\"PerpetuumSoft.Instrumentation.Model.Slider\" id=\"19\" Value=\"69.2307692307" +
            "69226\" Name=\"Slider1\"><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Exp" +
            "ressionBindingCollection\" id=\"20\" /><Elements type=\"PerpetuumSoft.Instrumentatio" +
            "n.Model.ElementCollection\" id=\"21\"><Item type=\"PerpetuumSoft.Instrumentation.Mod" +
            "el.LinearLevel\" id=\"22\" Distance=\"5.6843418860808015E-14\" Width=\"62.5\" Name=\"Lin" +
            "earLevel1\" Style=\"Default\" Value=\"69.2307692307692\" StartCap=\"Flat\" MinLimit=\"-2" +
            "\" EndCap=\"Flat\" Effect3D=\"Flat\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Si" +
            "mpleStroke\" id=\"23\" Width=\"10\" Color=\"132, 132, 132\" /><Expressions type=\"Perpet" +
            "uumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"24\"><Item type=\"P" +
            "erpetuumSoft.Instrumentation.Model.ExpressionBinding\" id=\"25\" Expression=\"Slider" +
            "1.Value\" PropertyName=\"Value\" /></Expressions><Fill type=\"PerpetuumSoft.Framewor" +
            "k.Drawing.SolidFill\" id=\"26\" Color=\"153, 205, 255\" /><Colors type=\"PerpetuumSoft" +
            ".Instrumentation.Model.Drawing.ColorSectionCollection\" id=\"27\" /></Item><Item ty" +
            "pe=\"PerpetuumSoft.Instrumentation.Model.Rectangle\" id=\"28\" Name=\"Rectangle2\" Siz" +
            "e=\"131.25;59.375\" Style=\"Default\" Center=\"190.62499999999983;528.125\"><Expressio" +
            "ns type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"29" +
            "\"><Item type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBinding\" id=\"30\" Exp" +
            "ression=\"r(0)\" PropertyName=\"Center\" /></Expressions><Stroke type=\"PerpetuumSoft" +
            ".Framework.Drawing.SimpleStroke\" id=\"31\" Width=\"10\" Color=\"148, 148, 148\" /><Fil" +
            "l type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"32\" Color=\"229, 229, 229\"" +
            " /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.Label\" id=\"33\" Text=\"6" +
            "9.2\" Size=\"131.25;59.375\" Style=\"Default\" Center=\"190.62499999999983;533.125\" Na" +
            "me=\"Label1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"34\" " +
            "FamilyName=\"Microsoft Sans Serif\" Size=\"11.25\" Underline=\"Off\" Strikeout=\"Off\" I" +
            "talic=\"Off\" Bold=\"On\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.E" +
            "xpressionBindingCollection\" id=\"35\"><Item type=\"PerpetuumSoft.Instrumentation.Mo" +
            "del.ExpressionBinding\" id=\"36\" Expression=\"format(Slider1.Value,&quot;0.0&quot;)" +
            "\" PropertyName=\"Text\" /><Item type=\"PerpetuumSoft.Instrumentation.Model.Expressi" +
            "onBinding\" id=\"37\" Expression=\"r(0) + [0,5]\" PropertyName=\"Center\" /></Expressio" +
            "ns><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"38\" Color=\"DimGray" +
            "\" /></Item></Elements></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.Tic" +
            "ks\" id=\"39\" Distance=\"62.5\" Style=\"Default\" Name=\"Ticks1\" Length=\"62.5\" SubDivis" +
            "ions=\"5\" SubLength=\"46.875\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Simple" +
            "Stroke\" id=\"40\" Width=\"5\" Style=\"None\" /><Colorizer type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.Drawing.SingleColorColorizer\" id=\"41\" Color=\"148, 148, 148\" /><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"42\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.ScaleLabels\" id" +
            "=\"43\" OddLabelsDistance=\"0\" Distance=\"184.375\" Style=\"Default\" Name=\"ScaleLabels" +
            "1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"44\" FamilyNam" +
            "e=\"Microsoft Sans Serif\" Size=\"12\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" " +
            "Bold=\"On\" /><Format type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"45\" UseCu" +
            "ltureSettings=\"true\" UseGroupSeparator=\"true\" /><Expressions type=\"PerpetuumSoft" +
            ".Instrumentation.Model.ExpressionBindingCollection\" id=\"46\" /></Item></Elements>" +
            "</Item></Elements></Item></Elements><Styles type=\"PerpetuumSoft.Instrumentation." +
            "Styles.StyleCollection\" id=\"47\"><Item type=\"PerpetuumSoft.Instrumentation.Styles" +
            ".Style\" id=\"48\" Name=\"Default\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.Sim" +
            "pleStroke\" id=\"49\" Width=\"1\" Style=\"None\" /><Font type=\"PerpetuumSoft.Framework." +
            "Drawing.FontDescriptor\" id=\"50\" FamilyName=\"Microsoft Sans Serif\" /></Item></Sty" +
            "les></root>")]
        public string Portador {
            get {
                return ((string)(this["Portador"]));
            }
            set {
                this["Portador"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FluxoCaixa {
            get {
                return ((string)(this["FluxoCaixa"]));
            }
            set {
                this["FluxoCaixa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DT_AvisoCert {
            get {
                return ((global::System.DateTime)(this["DT_AvisoCert"]));
            }
            set {
                this["DT_AvisoCert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BANCO_DADOS {
            get {
                return ((string)(this["BANCO_DADOS"]));
            }
            set {
                this["BANCO_DADOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SERVIDOR_BD {
            get {
                return ((string)(this["SERVIDOR_BD"]));
            }
            set {
                this["SERVIDOR_BD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tecno2012")]
        public string SENHA_BD {
            get {
                return ((string)(this["SENHA_BD"]));
            }
            set {
                this["SENHA_BD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ST_DESATIVAFINPOSTO {
            get {
                return ((string)(this["ST_DESATIVAFINPOSTO"]));
            }
            set {
                this["ST_DESATIVAFINPOSTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime DT_DESATIVAFINPOSTO {
            get {
                return ((global::System.DateTime)(this["DT_DESATIVAFINPOSTO"]));
            }
            set {
                this["DT_DESATIVAFINPOSTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_REMESSA {
            get {
                return ((string)(this["PATH_REMESSA"]));
            }
            set {
                this["PATH_REMESSA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PATH_RETORNO {
            get {
                return ((string)(this["PATH_RETORNO"]));
            }
            set {
                this["PATH_RETORNO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_XML_NFe_CTe {
            get {
                return ((string)(this["Path_XML_NFe_CTe"]));
            }
            set {
                this["Path_XML_NFe_CTe"] = value;
            }
        }
    }
}
