//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostoCombustivel.WS_LMC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.fazenda.pr.gov.br/wsdl/sefaws", ConfigurationName="WS_LMC.LMCWS")]
    public interface LMCWS {
        
        // CODEGEN: Generating message contract since the wrapper name (lmcAutorizacaoResult) of message lmcAutorizacaoResult does not match the default value (lmcAutorizacao)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        PostoCombustivel.WS_LMC.lmcAutorizacaoResult lmcAutorizacao(PostoCombustivel.WS_LMC.lmcAutorizacao request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lmcAutorizacao", WrapperNamespace="http://www.fazenda.pr.gov.br/wsdl/sefaws", IsWrapped=true)]
    public partial class lmcAutorizacao {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.fazenda.pr.gov.br/wsdl/sefaws", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xmlDados;
        
        public lmcAutorizacao() {
        }
        
        public lmcAutorizacao(string xmlDados) {
            this.xmlDados = xmlDados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="lmcAutorizacaoResult", WrapperNamespace="http://www.fazenda.pr.gov.br/wsdl/sefaws", IsWrapped=true)]
    public partial class lmcAutorizacaoResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;
        
        public lmcAutorizacaoResult() {
        }
        
        public lmcAutorizacaoResult(System.Xml.XmlElement Any) {
            this.Any = Any;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LMCWSChannel : PostoCombustivel.WS_LMC.LMCWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class LMCWSClient : System.ServiceModel.ClientBase<PostoCombustivel.WS_LMC.LMCWS>, PostoCombustivel.WS_LMC.LMCWS {
        
        public LMCWSClient() {
        }
        
        public LMCWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LMCWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LMCWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LMCWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PostoCombustivel.WS_LMC.lmcAutorizacaoResult PostoCombustivel.WS_LMC.LMCWS.lmcAutorizacao(PostoCombustivel.WS_LMC.lmcAutorizacao request) {
            return base.Channel.lmcAutorizacao(request);
        }
        
        public System.Xml.XmlElement lmcAutorizacao(string xmlDados) {
            PostoCombustivel.WS_LMC.lmcAutorizacao inValue = new PostoCombustivel.WS_LMC.lmcAutorizacao();
            inValue.xmlDados = xmlDados;
            PostoCombustivel.WS_LMC.lmcAutorizacaoResult retVal = ((PostoCombustivel.WS_LMC.LMCWS)(this)).lmcAutorizacao(inValue);
            return retVal.Any;
        }
    }
}
