//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerencia.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gerencia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;&lt;root type=&quot;PerpetuumSoft.Olap.DataCubeSettings&quot; id=&quot;1&quot; version=&quot;2&quot;&gt;&lt;DataCubeLayout type=&quot;PerpetuumSoft.Olap.DataCubeLayout&quot; id=&quot;2&quot;&gt;&lt;Facts type=&quot;PerpetuumSoft.Olap.FieldsCollection&quot; id=&quot;3&quot;&gt;&lt;Item type=&quot;PerpetuumSoft.Olap.Field&quot; id=&quot;4&quot; Format=&quot;0.00&quot; DisplayExpression=&quot;&quot; Expression=&quot;Vl_previsto&quot; Caption=&quot;Vl. Previsto&quot;&gt;&lt;Groups type=&quot;System.Collections.Hashtable&quot; id=&quot;5&quot; /&gt;&lt;/Item&gt;&lt;Item type=&quot;PerpetuumSoft.Olap.Field&quot; id=&quot;6&quot; Format=&quot;0.00&quot; DisplayExpression=&quot;&quot;  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string LAYOUT_CUBO {
            get {
                return ResourceManager.GetString("LAYOUT_CUBO", resourceCulture);
            }
        }
    }
}
