//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerencia.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Olap.DataCubeSettings\" id=\"1\" version=\"2\"><DataCubeLayout type=\"PerpetuumSoft.Ol" +
            "ap.DataCubeLayout\" id=\"2\"><Facts type=\"PerpetuumSoft.Olap.FieldsCollection\" id=\"" +
            "3\"><Item type=\"PerpetuumSoft.Olap.Field\" id=\"4\" Format=\"N2\" DisplayExpression=\"\"" +
            " Expression=\"Valor\" Caption=\"Valor Realizado\"><Groups type=\"System.Collections.H" +
            "ashtable\" id=\"5\" /></Item></Facts><YDimensions type=\"PerpetuumSoft.Olap.FieldsCo" +
            "llection\" id=\"6\"><Item type=\"PerpetuumSoft.Olap.Field\" id=\"7\" DisplayExpression=" +
            "\"Ds_empreendimento\" Expression=\"Id_empreendimento\" Caption=\"Empreendimento\" Widt" +
            "h=\"180\"><Groups type=\"System.Collections.Hashtable\" id=\"8\" /></Item><Item type=\"" +
            "PerpetuumSoft.Olap.Field\" id=\"9\" DisplayExpression=\"Ds_grupocf1\" Expression=\"Cd_" +
            "grupocf1\" Caption=\"Nivel 1\" Width=\"103\"><Groups type=\"System.Collections.Hashtab" +
            "le\" id=\"10\" /></Item><Item type=\"PerpetuumSoft.Olap.Field\" id=\"11\" DisplayExpres" +
            "sion=\"Ds_grupocf2\" Expression=\"Cd_grupocf2\" Caption=\"Nivel 2\" Width=\"79\"><Groups" +
            " type=\"System.Collections.Hashtable\" id=\"12\" /></Item><Item type=\"PerpetuumSoft." +
            "Olap.Field\" id=\"13\" DisplayExpression=\"Ds_grupocf3\" Expression=\"Cd_grupocf3\" Cap" +
            "tion=\"Nivel 3\" Width=\"246\"><Groups type=\"System.Collections.Hashtable\" id=\"14\" /" +
            "></Item><Item type=\"PerpetuumSoft.Olap.Field\" id=\"15\" DisplayExpression=\"Ds_grup" +
            "ocf4\" Expression=\"Cd_grupocf4\" Caption=\"Nivel 4\" Width=\"398\"><Groups type=\"Syste" +
            "m.Collections.Hashtable\" id=\"16\" /></Item></YDimensions><InactiveFields type=\"Pe" +
            "rpetuumSoft.Olap.FieldsCollection\" id=\"17\" /><XDimensions type=\"PerpetuumSoft.Ol" +
            "ap.FieldsCollection\" id=\"18\" /></DataCubeLayout></root>")]
        public string LAYOUT_CUB {
            get {
                return ((string)(this["LAYOUT_CUB"]));
            }
            set {
                this["LAYOUT_CUB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Olap.DataCubeSettings\" id=\"1\" version=\"2\"><DataCubeLayout type=\"PerpetuumSoft.Ol" +
            "ap.DataCubeLayout\" id=\"2\"><Facts type=\"PerpetuumSoft.Olap.FieldsCollection\" id=\"" +
            "3\"><Item type=\"PerpetuumSoft.Olap.Field\" id=\"4\" Format=\"N2\" DisplayExpression=\"\"" +
            " Expression=\"Vl_lancto\" Caption=\"Vl. Realizado\"><Groups type=\"System.Collections" +
            ".Hashtable\" id=\"5\" /></Item></Facts><YDimensions type=\"PerpetuumSoft.Olap.Fields" +
            "Collection\" id=\"6\"><Item type=\"PerpetuumSoft.Olap.Field\" id=\"7\" TotalLabel=\"Resu" +
            "ltado Empresa\" DisplayExpression=\"\" Expression=\"Cd_empresa\" Caption=\"Empresa\"><G" +
            "roups type=\"System.Collections.Hashtable\" id=\"8\" /></Item><Item type=\"PerpetuumS" +
            "oft.Olap.Field\" id=\"9\" TotalLabel=\"Resultado Nivel 3\" DisplayExpression=\"DS_Grup" +
            "oCF3\" Expression=\"CD_GrupoCF3\" Caption=\"Nivel 3\"><Groups type=\"System.Collection" +
            "s.Hashtable\" id=\"10\" /></Item><Item type=\"PerpetuumSoft.Olap.Field\" id=\"11\" Tota" +
            "lLabel=\"Resultado Nivel 4\" DisplayExpression=\"DS_GrupoCF4\" Expression=\"CD_GrupoC" +
            "F4\" Caption=\"Nivel 4\" Width=\"277\"><Groups type=\"System.Collections.Hashtable\" id" +
            "=\"12\" /></Item></YDimensions><InactiveFields type=\"PerpetuumSoft.Olap.FieldsColl" +
            "ection\" id=\"13\"><Item type=\"PerpetuumSoft.Olap.Field\" id=\"14\" TotalLabel=\"Result" +
            "ado Nivel 1\" DisplayExpression=\"DS_GrupoCF1\" Expression=\"CD_GrupoCF1\" Caption=\"N" +
            "ivel 1\"><Groups type=\"System.Collections.Hashtable\" id=\"15\" /></Item><Item type=" +
            "\"PerpetuumSoft.Olap.Field\" id=\"16\" TotalLabel=\"Resultado Nivel 2\" DisplayExpress" +
            "ion=\"DS_GrupoCF2\" Expression=\"CD_GrupoCF2\" Caption=\"Nivel 2\"><Groups type=\"Syste" +
            "m.Collections.Hashtable\" id=\"17\" /></Item><Item type=\"PerpetuumSoft.Olap.Field\" " +
            "id=\"18\" Format=\"N2\" DisplayExpression=\"\" Expression=\"Vl_previsto\" Caption=\"Vl. P" +
            "revisto\"><Groups type=\"System.Collections.Hashtable\" id=\"19\" /></Item><Item type" +
            "=\"PerpetuumSoft.Olap.Field\" id=\"20\" Format=\"N2\" DisplayExpression=\"\" Expression=" +
            "\"Vl_metaotimo\" Caption=\"Vl. Meta Otimo\"><Groups type=\"System.Collections.Hashtab" +
            "le\" id=\"21\" /></Item></InactiveFields><XDimensions type=\"PerpetuumSoft.Olap.Fiel" +
            "dsCollection\" id=\"22\"><Item type=\"PerpetuumSoft.Olap.Field\" id=\"23\" TotalLabel=\"" +
            "Resultado Ano\" DisplayExpression=\"\" Expression=\"Ano\" Caption=\"Ano\"><Groups type=" +
            "\"System.Collections.Hashtable\" id=\"24\" /></Item><Item type=\"PerpetuumSoft.Olap.F" +
            "ield\" id=\"25\" TotalLabel=\"Resultado Mês\" DisplayExpression=\"Messtr\" Expression=\"" +
            "Mes\" Caption=\"Mês\"><Groups type=\"System.Collections.Hashtable\" id=\"26\" /></Item>" +
            "</XDimensions></DataCubeLayout></root>")]
        public string LAYOUT_CUBO {
            get {
                return ((string)(this["LAYOUT_CUBO"]));
            }
            set {
                this["LAYOUT_CUBO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Charts.Chart\" id=\"1\" version=\"2\" Size=\"2143.75;768.75\" GridStep=\"50\" Name=\"Chart" +
            "\" MeasureUnit=\"Pixel\"><Parameters type=\"PerpetuumSoft.Instrumentation.Model.Para" +
            "meterCollection\" id=\"2\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model" +
            ".ExpressionBindingCollection\" id=\"3\" /><Bevel type=\"PerpetuumSoft.Instrumentatio" +
            "n.Model.StandardBevel\" id=\"4\" DownOffset=\"0\" CornerRadius=\"20\" UpOffset=\"0\"><Str" +
            "oke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"5\" Width=\"5\" Color=\"" +
            "DarkGray\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.LinearGradientFill\" id=\"" +
            "6\" Angle=\"270\" StartColor=\"213, 219, 226\" /><BevelShadow type=\"PerpetuumSoft.Fra" +
            "mework.Drawing.Shadow\" id=\"7\" DY=\"25\" DX=\"25\"><Fill type=\"PerpetuumSoft.Framewor" +
            "k.Drawing.LinearGradientFill\" id=\"8\" StartColor=\"Silver\" EndColor=\"223, 223, 223" +
            "\" /></BevelShadow></Bevel><Elements type=\"PerpetuumSoft.Instrumentation.Model.El" +
            "ementCollection\" id=\"9\"><Item type=\"PerpetuumSoft.Charts.ChartArea\" id=\"10\" Size" +
            "=\"2098.75;723.75\" Margins=\"0; 0; 0; 0\" Dock=\"Client\" Center=\"1059.375;371.875\" N" +
            "ame=\"ChartArea1\"><Palette type=\"PerpetuumSoft.Charts.PaletteRainbow\" id=\"11\" /><" +
            "Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollectio" +
            "n\" id=\"12\" /><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollecti" +
            "on\" id=\"13\"><Item type=\"PerpetuumSoft.Charts.Axis\" id=\"14\" IsDiscrete=\"true\" Nam" +
            "e=\"AxisX\"><Arrow type=\"PerpetuumSoft.Charts.SharpAngleAxisArrow\" id=\"15\" /><Stro" +
            "ke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"16\" Width=\"1\" Color=\"" +
            "48, 99, 153\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Expression" +
            "BindingCollection\" id=\"17\" /><Elements type=\"PerpetuumSoft.Instrumentation.Model" +
            ".ElementCollection\" id=\"18\"><Item type=\"PerpetuumSoft.Instrumentation.Model.Tick" +
            "s\" id=\"19\" Divisions=\"5\" Distance=\"0\" Origin=\"0\" Name=\"Ticks2\" Step=\"1\" Length=\"" +
            "31.25\" SubDivisions=\"9\" SubLength=\"15.625\"><Stroke type=\"PerpetuumSoft.Framework" +
            ".Drawing.SimpleStroke\" id=\"20\" Width=\"1\" /><Colorizer type=\"PerpetuumSoft.Instru" +
            "mentation.Model.Drawing.SingleColorColorizer\" id=\"21\" Color=\"48, 99, 154\" /><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"22\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.ScaleLabels\" id" +
            "=\"23\" OddLabelsDistance=\"0\" Dock=\"Outside\" Distance=\"51.20343017578125\" Name=\"Sc" +
            "aleLabels1\" Padding=\"31.25\" TextRotationMode=\"Screen\"><Colorizer type=\"Perpetuum" +
            "Soft.Instrumentation.Model.Drawing.SingleColorColorizer\" id=\"24\" Color=\"Black\" /" +
            "><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"25\" FamilyName=" +
            "\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" " +
            "Bold=\"Off\" /><Format type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"26\" UseC" +
            "ultureSettings=\"true\" UseGroupSeparator=\"true\" /><Expressions type=\"PerpetuumSof" +
            "t.Instrumentation.Model.ExpressionBindingCollection\" id=\"27\" /><Fill type=\"Perpe" +
            "tuumSoft.Framework.Drawing.EmptyFill\" id=\"28\" /></Item></Elements></Item><Item t" +
            "ype=\"PerpetuumSoft.Charts.Title\" id=\"29\" TextAngle=\"0\" Text=\"Venda Combustivel (" +
            "Litros)\" Size=\"2098.75;132.6568603515625\" DockingStyle=\"Outside\" DockingType=\"To" +
            "p\" Alignment=\"Center\" Center=\"1059.375;76.32843017578125\" Padding=\"93.75; 0; 0; " +
            "0\" Name=\"Title1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=" +
            "\"30\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Of" +
            "f\" Italic=\"On\" Bold=\"On\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Mode" +
            "l.ExpressionBindingCollection\" id=\"31\" /><TextFill type=\"PerpetuumSoft.Framework" +
            ".Drawing.SolidFill\" id=\"32\" Color=\"Blue\" /><Fill type=\"PerpetuumSoft.Framework.D" +
            "rawing.EmptyFill\" id=\"33\" /></Item><Item type=\"PerpetuumSoft.Charts.Legend\" id=\"" +
            "34\" Alignment=\"Near\" ColumnsCount=\"4\" DockingType=\"Top\" ItemMargins=\"10; 10; 10;" +
            " 10\" Name=\"Legenda1\" Center=\"536.28033447265625;188.57330322265625\" BadgeIndent=" +
            "\"0\" Size=\"1052.5606689453125;91.8328857421875\"><Font type=\"PerpetuumSoft.Framewo" +
            "rk.Drawing.FontDescriptor\" id=\"35\" FamilyName=\"Microsoft Sans Serif\" Size=\"6.75\"" +
            " Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"On\" /><TextFill type=\"Perpet" +
            "uumSoft.Framework.Drawing.SolidFill\" id=\"36\" Color=\"Black\" /><Expressions type=\"" +
            "PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"37\" /><Fill" +
            " type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"38\" /></Item><Item type=\"P" +
            "erpetuumSoft.Charts.Series\" id=\"39\" LegendExpression=\"\" SeriesSortingType=\"Ascen" +
            "ding\" DataSource=\"VendaDiaCombustivel\" AutoArgument=\"false\" Caption=\"Venda Dia\" " +
            "Name=\"sVendaDia\"><View type=\"PerpetuumSoft.Charts.BarSeriesView\" id=\"40\" /><Expr" +
            "essions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" i" +
            "d=\"41\" /><Bindings type=\"PerpetuumSoft.Charts.SeriesBindingCollection\" id=\"42\"><" +
            "Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"43\" SeriesValueName=\"Value\" P" +
            "ropertyName=\"qtd_vendida\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"" +
            "44\" SeriesValueName=\"Argument\" PropertyName=\"ds_produto\" /></Bindings><Elements " +
            "type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"45\"><Item type=" +
            "\"PerpetuumSoft.Charts.ValueLabels\" id=\"46\" Distance=\"10\" Name=\"Rótulos de Valor." +
            "2\" Angle=\"270\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.EmptyStroke\" id=\"47" +
            "\" /><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"48\" FamilyNa" +
            "me=\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Of" +
            "f\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Expressio" +
            "nBindingCollection\" id=\"49\" /><TextFill type=\"PerpetuumSoft.Framework.Drawing.So" +
            "lidFill\" id=\"50\" Color=\"Black\" /><TextFormat type=\"PerpetuumSoft.Framework.Text." +
            "TextFormat\" id=\"51\" UseCultureSettings=\"false\" FormatStyle=\"Number\" UseGroupSepa" +
            "rator=\"true\" DecimalPlaces=\"0\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.Emp" +
            "tyFill\" id=\"52\" /></Item></Elements><Values type=\"PerpetuumSoft.Charts.SeriesVal" +
            "ueCollection\" id=\"53\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" i" +
            "d=\"54\" Color=\"Orange\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.EmptyStrok" +
            "e\" id=\"55\" /></Item><Item type=\"PerpetuumSoft.Charts.Series\" id=\"56\" SeriesSorti" +
            "ngType=\"Ascending\" DataSource=\"AcumuladoMes\" AutoArgument=\"false\" Caption=\"Acumu" +
            "lado Mes\" Name=\"sAcumuladoMes\"><View type=\"PerpetuumSoft.Charts.BarSeriesView\" i" +
            "d=\"57\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindin" +
            "gCollection\" id=\"58\" /><Bindings type=\"PerpetuumSoft.Charts.SeriesBindingCollect" +
            "ion\" id=\"59\"><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"60\" SeriesValue" +
            "Name=\"Value\" PropertyName=\"qtd_vendida\" /><Item type=\"PerpetuumSoft.Charts.Serie" +
            "sBinding\" id=\"61\" SeriesValueName=\"Argument\" PropertyName=\"ds_produto\" /></Bindi" +
            "ngs><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"6" +
            "2\"><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"63\" Distance=\"10\" Position=" +
            "\"Center\" Name=\"Rótulos de Valor.1\" Angle=\"270\"><Stroke type=\"PerpetuumSoft.Frame" +
            "work.Drawing.EmptyStroke\" id=\"64\" /><Font type=\"PerpetuumSoft.Framework.Drawing." +
            "FontDescriptor\" id=\"65\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Underline=" +
            "\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft" +
            ".Instrumentation.Model.ExpressionBindingCollection\" id=\"66\" /><TextFill type=\"Pe" +
            "rpetuumSoft.Framework.Drawing.SolidFill\" id=\"67\" Color=\"Black\" /><TextFormat typ" +
            "e=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"68\" UseCultureSettings=\"false\" F" +
            "ormatStyle=\"Number\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\" /><Fill type=\"Per" +
            "petuumSoft.Framework.Drawing.EmptyFill\" id=\"69\" /></Item></Elements><Values type" +
            "=\"PerpetuumSoft.Charts.SeriesValueCollection\" id=\"70\" /><Fill type=\"PerpetuumSof" +
            "t.Framework.Drawing.SolidFill\" id=\"71\" Color=\"Tan\" /><Stroke type=\"PerpetuumSoft" +
            ".Framework.Drawing.EmptyStroke\" id=\"72\" /></Item><Item type=\"PerpetuumSoft.Chart" +
            "s.Series\" id=\"73\" SeriesSortingType=\"Ascending\" DataSource=\"VendaMesAnt\" AutoArg" +
            "ument=\"false\" Caption=\"Venda Mes Ant.\" Name=\"sVendaMesAnt\"><View type=\"Perpetuum" +
            "Soft.Charts.BarSeriesView\" id=\"74\" /><Expressions type=\"PerpetuumSoft.Instrument" +
            "ation.Model.ExpressionBindingCollection\" id=\"75\" /><Bindings type=\"PerpetuumSoft" +
            ".Charts.SeriesBindingCollection\" id=\"76\"><Item type=\"PerpetuumSoft.Charts.Series" +
            "Binding\" id=\"77\" SeriesValueName=\"Value\" PropertyName=\"qtd_vendida\" /><Item type" +
            "=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"78\" SeriesValueName=\"Argument\" Propert" +
            "yName=\"ds_produto\" /></Bindings><Elements type=\"PerpetuumSoft.Instrumentation.Mo" +
            "del.ElementCollection\" id=\"79\"><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=" +
            "\"80\" Distance=\"10\" Position=\"Center\" Name=\"Rótulos de Valor.4\" Angle=\"270\"><Stro" +
            "ke type=\"PerpetuumSoft.Framework.Drawing.EmptyStroke\" id=\"81\" /><Font type=\"Perp" +
            "etuumSoft.Framework.Drawing.FontDescriptor\" id=\"82\" FamilyName=\"Microsoft Sans S" +
            "erif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"83\" /><TextFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"84\" Col" +
            "or=\"Black\" /><TextFormat type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"85\" " +
            "UseCultureSettings=\"false\" FormatStyle=\"Number\" UseGroupSeparator=\"true\" Decimal" +
            "Places=\"0\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"86\" /></" +
            "Item></Elements><Values type=\"PerpetuumSoft.Charts.SeriesValueCollection\" id=\"87" +
            "\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"88\" Color=\"Green\"" +
            " /><Stroke type=\"PerpetuumSoft.Framework.Drawing.EmptyStroke\" id=\"89\" /></Item><" +
            "Item type=\"PerpetuumSoft.Charts.Series\" id=\"90\" SeriesSortingType=\"Ascending\" Da" +
            "taSource=\"AcumuladoMes\" AutoArgument=\"false\" Caption=\"Previsto Mes\" Name=\"sTende" +
            "nciaMes\"><View type=\"PerpetuumSoft.Charts.BarSeriesView\" id=\"91\" /><Expressions " +
            "type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"92\" /" +
            "><Bindings type=\"PerpetuumSoft.Charts.SeriesBindingCollection\" id=\"93\"><Item typ" +
            "e=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"94\" SeriesValueName=\"Value\" PropertyN" +
            "ame=\"qtd_tend\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"95\" SeriesV" +
            "alueName=\"Argument\" PropertyName=\"ds_produto\" /></Bindings><Elements type=\"Perpe" +
            "tuumSoft.Instrumentation.Model.ElementCollection\" id=\"96\"><Item type=\"PerpetuumS" +
            "oft.Charts.ValueLabels\" id=\"97\" Distance=\"10\" Position=\"Center\" Name=\"Rótulos de" +
            " Valor.3\" Angle=\"270\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.EmptyStroke\"" +
            " id=\"98\" /><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"99\" F" +
            "amilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Ita" +
            "lic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Ex" +
            "pressionBindingCollection\" id=\"100\" /><TextFill type=\"PerpetuumSoft.Framework.Dr" +
            "awing.SolidFill\" id=\"101\" Color=\"Black\" /><TextFormat type=\"PerpetuumSoft.Framew" +
            "ork.Text.TextFormat\" id=\"102\" UseCultureSettings=\"false\" FormatStyle=\"Number\" Us" +
            "eGroupSeparator=\"true\" DecimalPlaces=\"0\" /><Fill type=\"PerpetuumSoft.Framework.D" +
            "rawing.EmptyFill\" id=\"103\" /></Item></Elements><Values type=\"PerpetuumSoft.Chart" +
            "s.SeriesValueCollection\" id=\"104\" /><Fill type=\"PerpetuumSoft.Framework.Drawing." +
            "SolidFill\" id=\"105\" Color=\"Gold\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing" +
            ".EmptyStroke\" id=\"106\" /></Item><Item type=\"PerpetuumSoft.Charts.Axis\" id=\"107\" " +
            "Direction=\"Y\" MaxValue=\"110%\" Margins=\"0; 0; 312.5; 0\" Name=\"AxisY\"><Arrow type=" +
            "\"PerpetuumSoft.Charts.SharpAngleAxisArrow\" id=\"108\" /><Stroke type=\"PerpetuumSof" +
            "t.Framework.Drawing.SimpleStroke\" id=\"109\" Width=\"1\" Color=\"48, 99, 153\" /><Expr" +
            "essions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" i" +
            "d=\"110\" /><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\"" +
            " id=\"111\" /></Item></Elements></Item></Elements><Styles type=\"PerpetuumSoft.Inst" +
            "rumentation.Styles.StyleCollection\" id=\"112\"><Item type=\"PerpetuumSoft.Instrumen" +
            "tation.Styles.Style\" id=\"113\" Name=\"Default\"><Stroke type=\"PerpetuumSoft.Framewo" +
            "rk.Drawing.SimpleStroke\" id=\"114\" Width=\"1\" /><Font type=\"PerpetuumSoft.Framewor" +
            "k.Drawing.FontDescriptor\" id=\"115\" FamilyName=\"Microsoft Sans Serif\" /></Item><I" +
            "tem type=\"PerpetuumSoft.Instrumentation.Styles.Style\" id=\"116\" Name=\"Series1\"><F" +
            "ill type=\"PerpetuumSoft.Framework.Drawing.LinearGradientFill\" id=\"117\" StartColo" +
            "r=\"186, 250, 255\" EndColor=\"121, 217, 254\" /><Stroke type=\"PerpetuumSoft.Framewo" +
            "rk.Drawing.SimpleStroke\" id=\"118\" Width=\"5\" Color=\"213, 219, 226\" /></Item></Sty" +
            "les></root>")]
        public string LAYOUT_CHVENDACOMB {
            get {
                return ((string)(this["LAYOUT_CHVENDACOMB"]));
            }
            set {
                this["LAYOUT_CHVENDACOMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Charts.Chart\" id=\"1\" version=\"2\" Size=\"2146.875;768.75\" GridStep=\"50\" ShowGrid=\"" +
            "false\" Name=\"Chart\" MeasureUnit=\"Pixel\"><Parameters type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.ParameterCollection\" id=\"2\" /><Expressions type=\"PerpetuumSoft.Ins" +
            "trumentation.Model.ExpressionBindingCollection\" id=\"3\" /><Bevel type=\"PerpetuumS" +
            "oft.Instrumentation.Model.StandardBevel\" id=\"4\" DownOffset=\"0\" CornerRadius=\"20\"" +
            " UpOffset=\"0\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"5\"" +
            " Width=\"5\" Color=\"DarkGray\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.Linear" +
            "GradientFill\" id=\"6\" Angle=\"270\" StartColor=\"213, 219, 226\" /><BevelShadow type=" +
            "\"PerpetuumSoft.Framework.Drawing.Shadow\" id=\"7\" DY=\"25\" DX=\"25\"><Fill type=\"Perp" +
            "etuumSoft.Framework.Drawing.LinearGradientFill\" id=\"8\" StartColor=\"Silver\" EndCo" +
            "lor=\"223, 223, 223\" /></BevelShadow></Bevel><Elements type=\"PerpetuumSoft.Instru" +
            "mentation.Model.ElementCollection\" id=\"9\"><Item type=\"PerpetuumSoft.Charts.Chart" +
            "Area\" id=\"10\" Size=\"2101.875;723.75\" Margins=\"0; 0; 0; 0\" Dock=\"Client\" Center=\"" +
            "1060.9375;371.875\" PrimaryValueAxis=\"11\" Name=\"ChartArea1\"><Palette type=\"Perpet" +
            "uumSoft.Charts.PaletteRainbow\" id=\"12\" /><Expressions type=\"PerpetuumSoft.Instru" +
            "mentation.Model.ExpressionBindingCollection\" id=\"13\" /><Elements type=\"Perpetuum" +
            "Soft.Instrumentation.Model.ElementCollection\" id=\"14\"><Item type=\"PerpetuumSoft." +
            "Charts.Axis\" id=\"15\" IsDiscrete=\"true\" Name=\"AxisX\"><Arrow type=\"PerpetuumSoft.C" +
            "harts.SharpAngleAxisArrow\" id=\"16\" /><Stroke type=\"PerpetuumSoft.Framework.Drawi" +
            "ng.SimpleStroke\" id=\"17\" Width=\"1\" Color=\"48, 99, 153\" /><Expressions type=\"Perp" +
            "etuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"18\" /><Elements" +
            " type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"19\"><Item type" +
            "=\"PerpetuumSoft.Instrumentation.Model.Ticks\" id=\"20\" Divisions=\"5\" Distance=\"0\" " +
            "Origin=\"0\" Name=\"Ticks2\" Step=\"1\" Length=\"31.25\" SubDivisions=\"9\" SubLength=\"15." +
            "625\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"21\" Width=\"" +
            "1\" /><Colorizer type=\"PerpetuumSoft.Instrumentation.Model.Drawing.SingleColorCol" +
            "orizer\" id=\"22\" Color=\"48, 99, 154\" /><Expressions type=\"PerpetuumSoft.Instrumen" +
            "tation.Model.ExpressionBindingCollection\" id=\"23\" /></Item><Item type=\"Perpetuum" +
            "Soft.Instrumentation.Model.ScaleLabels\" id=\"24\" OddLabelsDistance=\"0\" Dock=\"Outs" +
            "ide\" Distance=\"51.203430175781257\" Name=\"ScaleLabels1\" Padding=\"31.25\" TextRotat" +
            "ionMode=\"Screen\"><Colorizer type=\"PerpetuumSoft.Instrumentation.Model.Drawing.Si" +
            "ngleColorColorizer\" id=\"25\" Color=\"Black\" /><Font type=\"PerpetuumSoft.Framework." +
            "Drawing.FontDescriptor\" id=\"26\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Un" +
            "derline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Format type=\"PerpetuumS" +
            "oft.Framework.Text.TextFormat\" id=\"27\" UseCultureSettings=\"true\" UseGroupSeparat" +
            "or=\"true\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBin" +
            "dingCollection\" id=\"28\" /></Item></Elements></Item><Item type=\"PerpetuumSoft.Cha" +
            "rts.Axis\" id=\"11\" Direction=\"Y\" MaxValue=\"110%\" Margins=\"0; 0; 312.5; 0\" Name=\"A" +
            "xisY\" MinValue=\"0\"><Arrow type=\"PerpetuumSoft.Charts.SharpAngleAxisArrow\" id=\"29" +
            "\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"30\" Width=\"1" +
            "\" Color=\"48, 99, 153\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.E" +
            "xpressionBindingCollection\" id=\"31\" /><Elements type=\"PerpetuumSoft.Instrumentat" +
            "ion.Model.ElementCollection\" id=\"32\" /></Item><Item type=\"PerpetuumSoft.Charts.T" +
            "itle\" id=\"33\" TextAngle=\"0\" Text=\"Venda Conveniencia (R$)\" Size=\"2101.875;132.65" +
            "68603515625\" DockingStyle=\"Outside\" DockingType=\"Top\" Alignment=\"Center\" Center=" +
            "\"1060.9375;76.32843017578125\" Padding=\"93.75; 0; 0; 0\" Name=\"Title1\"><Font type=" +
            "\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"34\" FamilyName=\"Microsoft S" +
            "ans Serif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"On\" Bold=\"On\" /><" +
            "Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollectio" +
            "n\" id=\"35\" /><TextFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"36\" " +
            "Color=\"Blue\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"37\" />" +
            "</Item><Item type=\"PerpetuumSoft.Charts.Legend\" id=\"38\" Alignment=\"Near\" Columns" +
            "Count=\"4\" DockingType=\"Top\" Margins=\"10; 10; 31.25; 10\" ItemMargins=\"10; 10; 10;" +
            " 10\" Name=\"Legenda1\" Center=\"456.81270599365234;189.16280110677084\" BadgeIndent=" +
            "\"0\" Size=\"893.62541198730469;93.011881510416671\"><Font type=\"PerpetuumSoft.Frame" +
            "work.Drawing.FontDescriptor\" id=\"39\" FamilyName=\"Microsoft Sans Serif\" Size=\"7\" " +
            "Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"On\" /><TextFill type=\"Perpetu" +
            "umSoft.Framework.Drawing.SolidFill\" id=\"40\" Color=\"Black\" /><Expressions type=\"P" +
            "erpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"41\" /></Item" +
            "><Item type=\"PerpetuumSoft.Charts.Series\" id=\"42\" SeriesSortingType=\"Ascending\" " +
            "DataSource=\"AcumuladoMesConv\" AutoArgument=\"false\" Caption=\"Acumulado Mes\" Name=" +
            "\"Série1\"><View type=\"PerpetuumSoft.Charts.BarSeriesView\" id=\"43\" /><Expressions " +
            "type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"44\" /" +
            "><Bindings type=\"PerpetuumSoft.Charts.SeriesBindingCollection\" id=\"45\"><Item typ" +
            "e=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"46\" SeriesValueName=\"Value\" PropertyN" +
            "ame=\"Vl_venda\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"47\" SeriesV" +
            "alueName=\"Argument\" PropertyName=\"Grupo\" /><Item type=\"PerpetuumSoft.Charts.Seri" +
            "esBinding\" id=\"48\" SeriesValueName=\"UserData\" PropertyName=\"Pc_representatividad" +
            "e\" /></Bindings><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementColle" +
            "ction\" id=\"49\"><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"50\" Distance=\"1" +
            "0\" Position=\"Center\" Name=\"Rótulos de Valor.1\" Angle=\"270\"><Stroke type=\"Perpetu" +
            "umSoft.Framework.Drawing.EmptyStroke\" id=\"51\" /><Font type=\"PerpetuumSoft.Framew" +
            "ork.Drawing.FontDescriptor\" id=\"52\" FamilyName=\"Microsoft Sans Serif\" Size=\"9.75" +
            "\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"P" +
            "erpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"53\" /><TextF" +
            "ill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"54\" Color=\"Black\" /><Te" +
            "xtFormat type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"55\" UseCultureSettin" +
            "gs=\"false\" FormatStyle=\"Number\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\" /></I" +
            "tem><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"56\" Formula=\"UserData\" Dis" +
            "tance=\"10\" Name=\"Rótulos de Valor.2\"><Stroke type=\"PerpetuumSoft.Framework.Drawi" +
            "ng.EmptyStroke\" id=\"57\" /><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescri" +
            "ptor\" id=\"58\" FamilyName=\"Microsoft Sans Serif\" Size=\"9.75\" Underline=\"Off\" Stri" +
            "keout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft.Instrumen" +
            "tation.Model.ExpressionBindingCollection\" id=\"59\" /><TextFill type=\"PerpetuumSof" +
            "t.Framework.Drawing.SolidFill\" id=\"60\" Color=\"Black\" /><TextFormat type=\"Perpetu" +
            "umSoft.Framework.Text.TextFormat\" id=\"61\" UseCultureSettings=\"false\" FormatStyle" +
            "=\"Percentage\" UseGroupSeparator=\"true\" /></Item></Elements><Values type=\"Perpetu" +
            "umSoft.Charts.SeriesValueCollection\" id=\"62\" /><Fill type=\"PerpetuumSoft.Framewo" +
            "rk.Drawing.SolidFill\" id=\"63\" Color=\"Tan\" /><Stroke type=\"PerpetuumSoft.Framewor" +
            "k.Drawing.EmptyStroke\" id=\"64\" /></Item><Item type=\"PerpetuumSoft.Charts.Series\"" +
            " id=\"65\" SeriesSortingType=\"Ascending\" DataSource=\"VendaMesAntConv\" AutoArgument" +
            "=\"false\" Caption=\"Venda Mes Ant.\" Name=\"Série4\"><View type=\"PerpetuumSoft.Charts" +
            ".BarSeriesView\" id=\"66\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model" +
            ".ExpressionBindingCollection\" id=\"67\" /><Palette type=\"PerpetuumSoft.Charts.Cust" +
            "omPalette\" id=\"68\"><Items type=\"PerpetuumSoft.Charts.CustomPaletteItemCollection" +
            "\" id=\"69\"><Item type=\"PerpetuumSoft.Charts.CustomPaletteItem\" id=\"70\" Color=\"\"><" +
            "Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"71\" Color=\"Green\" /></" +
            "Item></Items></Palette><Bindings type=\"PerpetuumSoft.Charts.SeriesBindingCollect" +
            "ion\" id=\"72\"><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"73\" SeriesValue" +
            "Name=\"Value\" PropertyName=\"Vl_venda\" /><Item type=\"PerpetuumSoft.Charts.SeriesBi" +
            "nding\" id=\"74\" SeriesValueName=\"Argument\" PropertyName=\"Grupo\" /></Bindings><Ele" +
            "ments type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"75\"><Item" +
            " type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"76\" Distance=\"10\" Position=\"Center\"" +
            " Name=\"Rótulos de Valor.4\" Angle=\"270\"><Font type=\"PerpetuumSoft.Framework.Drawi" +
            "ng.FontDescriptor\" id=\"77\" FamilyName=\"Microsoft Sans Serif\" Size=\"9.75\" Underli" +
            "ne=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumS" +
            "oft.Instrumentation.Model.ExpressionBindingCollection\" id=\"78\" /><TextFill type=" +
            "\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"79\" Color=\"Black\" /><TextFormat " +
            "type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"80\" UseCultureSettings=\"false" +
            "\" FormatStyle=\"Number\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\" /></Item></Ele" +
            "ments><Values type=\"PerpetuumSoft.Charts.SeriesValueCollection\" id=\"81\" /><Strok" +
            "e type=\"PerpetuumSoft.Framework.Drawing.EmptyStroke\" id=\"82\" /></Item><Item type" +
            "=\"PerpetuumSoft.Charts.Series\" id=\"83\" SeriesSortingType=\"Ascending\" DataSource=" +
            "\"AcumuladoMesConv\" AutoArgument=\"false\" Caption=\"Previsto Mes\" Name=\"Série3\"><Vi" +
            "ew type=\"PerpetuumSoft.Charts.BarSeriesView\" id=\"84\" /><Expressions type=\"Perpet" +
            "uumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"85\" /><Bindings t" +
            "ype=\"PerpetuumSoft.Charts.SeriesBindingCollection\" id=\"86\"><Item type=\"Perpetuum" +
            "Soft.Charts.SeriesBinding\" id=\"87\" SeriesValueName=\"Value\" PropertyName=\"Vl_tend" +
            "\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"88\" SeriesValueName=\"Arg" +
            "ument\" PropertyName=\"Grupo\" /></Bindings><Elements type=\"PerpetuumSoft.Instrumen" +
            "tation.Model.ElementCollection\" id=\"89\"><Item type=\"PerpetuumSoft.Charts.ValueLa" +
            "bels\" id=\"90\" Distance=\"10\" Position=\"Center\" Name=\"Rótulos de Valor.3\" Angle=\"2" +
            "70\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"91\" FamilyNa" +
            "me=\"Microsoft Sans Serif\" Size=\"9.75\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Of" +
            "f\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Expressio" +
            "nBindingCollection\" id=\"92\" /><TextFill type=\"PerpetuumSoft.Framework.Drawing.So" +
            "lidFill\" id=\"93\" Color=\"Black\" /><TextFormat type=\"PerpetuumSoft.Framework.Text." +
            "TextFormat\" id=\"94\" UseCultureSettings=\"false\" FormatStyle=\"Number\" UseGroupSepa" +
            "rator=\"true\" DecimalPlaces=\"0\" /></Item></Elements><Values type=\"PerpetuumSoft.C" +
            "harts.SeriesValueCollection\" id=\"95\" /><Fill type=\"PerpetuumSoft.Framework.Drawi" +
            "ng.SolidFill\" id=\"96\" Color=\"Gold\" /></Item></Elements></Item></Elements><Styles" +
            " type=\"PerpetuumSoft.Instrumentation.Styles.StyleCollection\" id=\"97\"><Item type=" +
            "\"PerpetuumSoft.Instrumentation.Styles.Style\" id=\"98\" Name=\"Default\"><Stroke type" +
            "=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"99\" Width=\"1\" /><Font type=\"" +
            "PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"100\" FamilyName=\"Microsoft S" +
            "ans Serif\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Styles.Style\" id=\"" +
            "101\" Name=\"Series1\"><Fill type=\"PerpetuumSoft.Framework.Drawing.LinearGradientFi" +
            "ll\" id=\"102\" StartColor=\"186, 250, 255\" EndColor=\"121, 217, 254\" /><Stroke type=" +
            "\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"103\" Width=\"5\" Color=\"213, 21" +
            "9, 226\" /></Item></Styles></root>")]
        public string LAYOUT_CHVENDACONV {
            get {
                return ((string)(this["LAYOUT_CHVENDACONV"]));
            }
            set {
                this["LAYOUT_CHVENDACONV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Charts.Chart\" id=\"1\" version=\"2\" Size=\"2150;906.25\" GridStep=\"50\" ShowGrid=\"fals" +
            "e\" Name=\"Chart\" MeasureUnit=\"Pixel\"><Parameters type=\"PerpetuumSoft.Instrumentat" +
            "ion.Model.ParameterCollection\" id=\"2\" /><Expressions type=\"PerpetuumSoft.Instrum" +
            "entation.Model.ExpressionBindingCollection\" id=\"3\" /><Bevel type=\"PerpetuumSoft." +
            "Instrumentation.Model.StandardBevel\" id=\"4\" DownOffset=\"0\" CornerRadius=\"20\" UpO" +
            "ffset=\"0\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"5\" Wid" +
            "th=\"5\" Color=\"DarkGray\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.LinearGrad" +
            "ientFill\" id=\"6\" Angle=\"270\" StartColor=\"213, 219, 226\" /><BevelShadow type=\"Per" +
            "petuumSoft.Framework.Drawing.Shadow\" id=\"7\" DY=\"25\" DX=\"25\"><Fill type=\"Perpetuu" +
            "mSoft.Framework.Drawing.LinearGradientFill\" id=\"8\" StartColor=\"Silver\" EndColor=" +
            "\"223, 223, 223\" /></BevelShadow></Bevel><Elements type=\"PerpetuumSoft.Instrument" +
            "ation.Model.ElementCollection\" id=\"9\"><Item type=\"PerpetuumSoft.Charts.ChartArea" +
            "\" id=\"10\" Size=\"2105;861.25\" Margins=\"0; 0; 0; 0\" Dock=\"Client\" Center=\"1062.5;4" +
            "40.625\" PrimaryValueAxis=\"11\" Name=\"ChartArea1\"><Palette type=\"PerpetuumSoft.Cha" +
            "rts.PaletteRainbow\" id=\"12\" /><Expressions type=\"PerpetuumSoft.Instrumentation.M" +
            "odel.ExpressionBindingCollection\" id=\"13\" /><Elements type=\"PerpetuumSoft.Instru" +
            "mentation.Model.ElementCollection\" id=\"14\"><Item type=\"PerpetuumSoft.Charts.Axis" +
            "\" id=\"15\" IsDiscrete=\"true\" Name=\"AxisX\"><Colorizer type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.Drawing.SingleColorColorizer\" id=\"16\" Color=\"Black\" /><Arrow type=" +
            "\"PerpetuumSoft.Charts.SharpAngleAxisArrow\" id=\"17\" /><Stroke type=\"PerpetuumSoft" +
            ".Framework.Drawing.SimpleStroke\" id=\"18\" Width=\"1\" Color=\"48, 99, 153\" /><Expres" +
            "sions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=" +
            "\"19\" /><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id" +
            "=\"20\"><Item type=\"PerpetuumSoft.Instrumentation.Model.Ticks\" id=\"21\" Divisions=\"" +
            "5\" Distance=\"0\" Origin=\"0\" Name=\"Ticks2\" Step=\"1\" Length=\"31.25\" SubDivisions=\"1" +
            "\" SubLength=\"15.625\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\"" +
            " id=\"22\" Width=\"1\" /><Colorizer type=\"PerpetuumSoft.Instrumentation.Model.Drawin" +
            "g.SingleColorColorizer\" id=\"23\" Color=\"Black\" /><Expressions type=\"PerpetuumSoft" +
            ".Instrumentation.Model.ExpressionBindingCollection\" id=\"24\" /></Item><Item type=" +
            "\"PerpetuumSoft.Instrumentation.Model.ScaleLabels\" id=\"25\" OddLabelsDistance=\"0\" " +
            "Dock=\"Outside\" Distance=\"51.20343017578125\" Name=\"ScaleLabels1\" Padding=\"31.25\" " +
            "TextRotationMode=\"Screen\"><Colorizer type=\"PerpetuumSoft.Instrumentation.Model.D" +
            "rawing.SingleColorColorizer\" id=\"26\" Color=\"0, 64, 0\" /><Font type=\"PerpetuumSof" +
            "t.Framework.Drawing.FontDescriptor\" id=\"27\" FamilyName=\"Microsoft Sans Serif\" Si" +
            "ze=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Format type" +
            "=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"28\" UseCultureSettings=\"true\" Use" +
            "GroupSeparator=\"true\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.E" +
            "xpressionBindingCollection\" id=\"29\" /></Item><Item type=\"PerpetuumSoft.Instrumen" +
            "tation.Model.ScaleTitle\" id=\"30\" OddLabelsDistance=\"0\" Dock=\"Inside\" Distance=\"-" +
            "19.953430175781254\" Text=\"Horas\" Name=\"Título da Escala1\" TextAlignment=\"Far\" Te" +
            "xtRotationMode=\"Screen\"><Colorizer type=\"PerpetuumSoft.Instrumentation.Model.Dra" +
            "wing.SingleColorColorizer\" id=\"31\" Color=\"Maroon\" /><Font type=\"PerpetuumSoft.Fr" +
            "amework.Drawing.FontDescriptor\" id=\"32\" FamilyName=\"Microsoft Sans Serif\" Size=\"" +
            "8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"On\" Bold=\"On\" /><Format type=\"Perp" +
            "etuumSoft.Framework.Text.TextFormat\" id=\"33\" UseCultureSettings=\"true\" UseGroupS" +
            "eparator=\"true\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Express" +
            "ionBindingCollection\" id=\"34\" /></Item><Item type=\"PerpetuumSoft.Charts.GridLine" +
            "s\" id=\"35\" Style=\"Default\" Name=\"Linhas do Grid1\" UseDescreteValues=\"true\"><Stro" +
            "ke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"36\" Width=\"1\" Color=\"" +
            "15, 0, 0, 0\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Expression" +
            "BindingCollection\" id=\"37\" /></Item></Elements></Item><Item type=\"PerpetuumSoft." +
            "Charts.Axis\" id=\"11\" Direction=\"Y\" MaxValue=\"110%\" Margins=\"0; 0; 312.5; 0\" Name" +
            "=\"AxisY\" MinValue=\"0\"><Arrow type=\"PerpetuumSoft.Charts.SharpAngleAxisArrow\" id=" +
            "\"38\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"39\" Width" +
            "=\"1\" Color=\"48, 99, 153\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Mode" +
            "l.ExpressionBindingCollection\" id=\"40\" /><Elements type=\"PerpetuumSoft.Instrumen" +
            "tation.Model.ElementCollection\" id=\"41\" /></Item><Item type=\"PerpetuumSoft.Chart" +
            "s.Title\" id=\"42\" TextAngle=\"0\" Text=\"Abastecidas por Hora\" Size=\"2105;132.656860" +
            "3515625\" DockingStyle=\"Outside\" DockingType=\"Top\" Alignment=\"Center\" Center=\"106" +
            "2.5;76.32843017578125\" Padding=\"93.75; 0; 0; 0\" Name=\"Title1\"><Font type=\"Perpet" +
            "uumSoft.Framework.Drawing.FontDescriptor\" id=\"43\" FamilyName=\"Microsoft Sans Ser" +
            "if\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"On\" Bold=\"On\" /><Express" +
            "ions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"" +
            "44\" /><TextFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"45\" Color=\"" +
            "Blue\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"46\" /></Item>" +
            "<Item type=\"PerpetuumSoft.Charts.Series\" id=\"47\" SeriesSortingType=\"Ascending\" D" +
            "ataSource=\"AbastecidasDia\" AutoArgument=\"false\" Caption=\"\" Name=\"Série1\"><View t" +
            "ype=\"PerpetuumSoft.Charts.LineSeriesView\" id=\"48\" DefaultColor=\"Black\" /><Expres" +
            "sions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=" +
            "\"49\" /><Bindings type=\"PerpetuumSoft.Charts.SeriesBindingCollection\" id=\"50\"><It" +
            "em type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"51\" SeriesValueName=\"Value\" Pro" +
            "pertyName=\"Qt_abastecida\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"" +
            "52\" SeriesValueName=\"Argument\" PropertyName=\"Hora\" /><Item type=\"PerpetuumSoft.C" +
            "harts.SeriesBinding\" id=\"53\" SeriesValueName=\"UserData\" PropertyName=\"Tot_volume" +
            "abastecido\" /></Bindings><Elements type=\"PerpetuumSoft.Instrumentation.Model.Ele" +
            "mentCollection\" id=\"54\"><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"55\" Di" +
            "stance=\"10\" Name=\"Rótulos de Valor.1\"><Font type=\"PerpetuumSoft.Framework.Drawin" +
            "g.FontDescriptor\" id=\"56\" FamilyName=\"Microsoft Sans Serif\" Size=\"9.75\" Underlin" +
            "e=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumSo" +
            "ft.Instrumentation.Model.ExpressionBindingCollection\" id=\"57\" /><TextFill type=\"" +
            "PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"58\" Color=\"Black\" /><TextFormat t" +
            "ype=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"59\" UseCultureSettings=\"true\" " +
            "UseGroupSeparator=\"true\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill" +
            "\" id=\"60\" /></Item><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"61\" Formula" +
            "=\"UserData\" Distance=\"10\" Name=\"Rótulos de Valor.2\" Shift=\"0;62.5\"><Font type=\"P" +
            "erpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"62\" FamilyName=\"Microsoft San" +
            "s Serif\" Size=\"7\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Exp" +
            "ressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" " +
            "id=\"63\" /><TextFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"64\" Col" +
            "or=\"Green\" /><TextFormat type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"65\" " +
            "UseCultureSettings=\"false\" FormatStyle=\"Number\" UseGroupSeparator=\"true\" Decimal" +
            "Places=\"0\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"66\" /></" +
            "Item></Elements><Values type=\"PerpetuumSoft.Charts.SeriesValueCollection\" id=\"67" +
            "\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.Label\" id=\"68\" Text=\"" +
            "Quantidade\" Size=\"300;50\" TextAlign=\"MiddleLeft\" Center=\"200;200\" Name=\"Rótulo1\"" +
            "><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"69\" FamilyName=" +
            "\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" " +
            "Bold=\"On\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBin" +
            "dingCollection\" id=\"70\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\"" +
            " id=\"71\" Color=\"Black\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model." +
            "Label\" id=\"72\" Text=\"Volume\" Size=\"300;50\" TextAlign=\"MiddleLeft\" Center=\"200;25" +
            "0\" Name=\"Rótulo2\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id" +
            "=\"73\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"O" +
            "ff\" Italic=\"Off\" Bold=\"On\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Mo" +
            "del.ExpressionBindingCollection\" id=\"74\" /><Fill type=\"PerpetuumSoft.Framework.D" +
            "rawing.SolidFill\" id=\"75\" Color=\"Green\" /></Item></Elements></Item></Elements><S" +
            "tyles type=\"PerpetuumSoft.Instrumentation.Styles.StyleCollection\" id=\"76\"><Item " +
            "type=\"PerpetuumSoft.Instrumentation.Styles.Style\" id=\"77\" Name=\"Default\"><Stroke" +
            " type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"78\" Width=\"1\" /><Font t" +
            "ype=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"79\" FamilyName=\"Microso" +
            "ft Sans Serif\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Styles.Style\" " +
            "id=\"80\" Name=\"Series1\"><Fill type=\"PerpetuumSoft.Framework.Drawing.LinearGradien" +
            "tFill\" id=\"81\" StartColor=\"186, 250, 255\" EndColor=\"121, 217, 254\" /><Stroke typ" +
            "e=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"82\" Width=\"5\" Color=\"213, 2" +
            "19, 226\" /></Item></Styles></root>")]
        public string LAYOUT_ABASTDIA {
            get {
                return ((string)(this["LAYOUT_ABASTDIA"]));
            }
            set {
                this["LAYOUT_ABASTDIA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Charts.Chart\" id=\"1\" version=\"2\" Size=\"2140.625;978.125\" GridStep=\"50\" ShowGrid=" +
            "\"false\" Name=\"Chart\" MeasureUnit=\"Pixel\"><Parameters type=\"PerpetuumSoft.Instrum" +
            "entation.Model.ParameterCollection\" id=\"2\" /><Expressions type=\"PerpetuumSoft.In" +
            "strumentation.Model.ExpressionBindingCollection\" id=\"3\" /><Bevel type=\"Perpetuum" +
            "Soft.Instrumentation.Model.StandardBevel\" id=\"4\" DownOffset=\"0\" CornerRadius=\"20" +
            "\" UpOffset=\"0\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"5" +
            "\" Width=\"5\" Color=\"DarkGray\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.Linea" +
            "rGradientFill\" id=\"6\" Angle=\"270\" StartColor=\"213, 219, 226\" /><BevelShadow type" +
            "=\"PerpetuumSoft.Framework.Drawing.Shadow\" id=\"7\" DY=\"25\" DX=\"25\"><Fill type=\"Per" +
            "petuumSoft.Framework.Drawing.LinearGradientFill\" id=\"8\" StartColor=\"Silver\" EndC" +
            "olor=\"223, 223, 223\" /></BevelShadow></Bevel><Elements type=\"PerpetuumSoft.Instr" +
            "umentation.Model.ElementCollection\" id=\"9\"><Item type=\"PerpetuumSoft.Charts.Char" +
            "tArea\" id=\"10\" Size=\"2095.625;933.125\" Margins=\"0; 0; 0; 0\" Dock=\"Client\" Center" +
            "=\"1057.8125;476.5625\" PrimaryValueAxis=\"11\" Name=\"ChartArea1\"><Palette type=\"Per" +
            "petuumSoft.Charts.PaletteRainbow\" id=\"12\" /><Expressions type=\"PerpetuumSoft.Ins" +
            "trumentation.Model.ExpressionBindingCollection\" id=\"13\" /><Elements type=\"Perpet" +
            "uumSoft.Instrumentation.Model.ElementCollection\" id=\"14\"><Item type=\"PerpetuumSo" +
            "ft.Charts.Axis\" id=\"15\" IsDiscrete=\"true\" Name=\"AxisX\"><Arrow type=\"PerpetuumSof" +
            "t.Charts.SharpAngleAxisArrow\" id=\"16\" /><Stroke type=\"PerpetuumSoft.Framework.Dr" +
            "awing.SimpleStroke\" id=\"17\" Width=\"1\" /><Expressions type=\"PerpetuumSoft.Instrum" +
            "entation.Model.ExpressionBindingCollection\" id=\"18\" /><Elements type=\"PerpetuumS" +
            "oft.Instrumentation.Model.ElementCollection\" id=\"19\"><Item type=\"PerpetuumSoft.I" +
            "nstrumentation.Model.Ticks\" id=\"20\" Divisions=\"5\" Distance=\"0\" Origin=\"0\" Name=\"" +
            "Ticks2\" Step=\"1\" Length=\"31.25\" SubDivisions=\"1\" SubLength=\"15.625\"><Stroke type" +
            "=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"21\" Width=\"1\" /><Colorizer t" +
            "ype=\"PerpetuumSoft.Instrumentation.Model.Drawing.SingleColorColorizer\" id=\"22\" C" +
            "olor=\"48, 99, 154\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.Expr" +
            "essionBindingCollection\" id=\"23\" /></Item><Item type=\"PerpetuumSoft.Instrumentat" +
            "ion.Model.ScaleLabels\" id=\"24\" OddLabelsDistance=\"0\" Dock=\"Outside\" Distance=\"51" +
            ".20343017578125\" Name=\"ScaleLabels1\" Padding=\"31.25\" TextRotationMode=\"Screen\"><" +
            "Colorizer type=\"PerpetuumSoft.Instrumentation.Model.Drawing.SingleColorColorizer" +
            "\" id=\"25\" Color=\"Black\" /><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescri" +
            "ptor\" id=\"26\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Stri" +
            "keout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Format type=\"PerpetuumSoft.Framework.Text" +
            ".TextFormat\" id=\"27\" UseCultureSettings=\"true\" UseGroupSeparator=\"true\" /><Expre" +
            "ssions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id" +
            "=\"28\" /></Item></Elements></Item><Item type=\"PerpetuumSoft.Charts.Axis\" id=\"11\" " +
            "Direction=\"Y\" MaxValue=\"110%\" Margins=\"0; 0; 312.5; 0\" Name=\"AxisY\" MinValue=\"0\"" +
            "><Arrow type=\"PerpetuumSoft.Charts.SharpAngleAxisArrow\" id=\"29\" /><Stroke type=\"" +
            "PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"30\" Width=\"1\" /><Expressions t" +
            "ype=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"31\" />" +
            "<Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"32\" /" +
            "></Item><Item type=\"PerpetuumSoft.Charts.Title\" id=\"33\" TextAngle=\"0\" Text=\"Esto" +
            "que Atual Combustivel (Litros)\" Size=\"2095.625;132.6568603515625\" DockingStyle=\"" +
            "Outside\" DockingType=\"Top\" Alignment=\"Center\" Center=\"1057.8125;76.3284301757812" +
            "5\" Padding=\"93.75; 0; 0; 0\" Name=\"Title1\"><Font type=\"PerpetuumSoft.Framework.Dr" +
            "awing.FontDescriptor\" id=\"34\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Unde" +
            "rline=\"Off\" Strikeout=\"Off\" Italic=\"On\" Bold=\"On\" /><Expressions type=\"Perpetuum" +
            "Soft.Instrumentation.Model.ExpressionBindingCollection\" id=\"35\" /><TextFill type" +
            "=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"36\" Color=\"Blue\" /><Fill type=\"" +
            "PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"37\" /></Item><Item type=\"Perpetuu" +
            "mSoft.Charts.Series\" id=\"38\" Sort=\"Ds_abreviadaProduto\" SortingType=\"Ascending\" " +
            "DataSource=\"EstoqueCombustivel\" AutoArgument=\"false\" Caption=\"Litragem\" Name=\"Sé" +
            "rie1\"><View type=\"PerpetuumSoft.Charts.BarSeriesView\" id=\"39\" /><Expressions typ" +
            "e=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"40\" /><B" +
            "indings type=\"PerpetuumSoft.Charts.SeriesBindingCollection\" id=\"41\"><Item type=\"" +
            "PerpetuumSoft.Charts.SeriesBinding\" id=\"42\" SeriesValueName=\"Value\" PropertyName" +
            "=\"Tot_saldo\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"43\" SeriesVal" +
            "ueName=\"Argument\" PropertyName=\"Ds_abreviadaProduto\" /><Item type=\"PerpetuumSoft" +
            ".Charts.SeriesBinding\" id=\"44\" SeriesValueName=\"UserData\" PropertyName=\"Vl_medio" +
            "\" /></Bindings><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollec" +
            "tion\" id=\"45\"><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"46\" Distance=\"10" +
            "\" Name=\"Rótulos de Valor.1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDesc" +
            "riptor\" id=\"47\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" St" +
            "rikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft.Instrum" +
            "entation.Model.ExpressionBindingCollection\" id=\"48\" /><TextFill type=\"PerpetuumS" +
            "oft.Framework.Drawing.SolidFill\" id=\"49\" Color=\"Black\" /><TextFormat type=\"Perpe" +
            "tuumSoft.Framework.Text.TextFormat\" id=\"50\" UseCultureSettings=\"false\" FormatSty" +
            "le=\"Number\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\" /><Fill type=\"PerpetuumSo" +
            "ft.Framework.Drawing.EmptyFill\" id=\"51\" /></Item><Item type=\"PerpetuumSoft.Chart" +
            "s.ValueLabels\" id=\"52\" Formula=\" Value / UserData\" Distance=\"10\" Position=\"Cente" +
            "r\" Name=\"Rótulos de Valor.3\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDes" +
            "criptor\" id=\"53\" FamilyName=\"Microsoft Sans Serif\" Size=\"9.75\" Underline=\"Off\" S" +
            "trikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft.Instru" +
            "mentation.Model.ExpressionBindingCollection\" id=\"54\" /><TextFill type=\"Perpetuum" +
            "Soft.Framework.Drawing.SolidFill\" id=\"55\" Color=\"Blue\" /><TextFormat type=\"Perpe" +
            "tuumSoft.Framework.Text.TextFormat\" id=\"56\" UseCultureSettings=\"false\" FormatSty" +
            "le=\"Number\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\" /><Fill type=\"PerpetuumSo" +
            "ft.Framework.Drawing.EmptyFill\" id=\"57\" /></Item></Elements><Values type=\"Perpet" +
            "uumSoft.Charts.SeriesValueCollection\" id=\"58\" /><Fill type=\"PerpetuumSoft.Framew" +
            "ork.Drawing.LinearGradientFill\" id=\"59\" StartColor=\"170, 0, 128, 0\" EndColor=\"14" +
            "9, 173, 255, 47\" /></Item><Item type=\"PerpetuumSoft.Charts.Series\" id=\"60\" Serie" +
            "sSortingType=\"Ascending\" DataSource=\"TotalEstoque\" AutoArgument=\"false\" Caption=" +
            "\"Valor\" Name=\"Série2\"><View type=\"PerpetuumSoft.Charts.BarSeriesView\" id=\"61\" />" +
            "<Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollecti" +
            "on\" id=\"62\" /><Bindings type=\"PerpetuumSoft.Charts.SeriesBindingCollection\" id=\"" +
            "63\"><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"64\" SeriesValueName=\"Val" +
            "ue\" PropertyName=\"Column1\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=" +
            "\"65\" SeriesValueName=\"Argument\" PropertyName=\"label\" /></Bindings><Elements type" +
            "=\"PerpetuumSoft.Instrumentation.Model.ElementCollection\" id=\"66\"><Item type=\"Per" +
            "petuumSoft.Charts.ValueLabels\" id=\"67\" Distance=\"10\" Name=\"Rótulos de Valor.2\"><" +
            "Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" id=\"68\" FamilyName=\"M" +
            "icrosoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bo" +
            "ld=\"Off\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBind" +
            "ingCollection\" id=\"69\" /><TextFill type=\"PerpetuumSoft.Framework.Drawing.SolidFi" +
            "ll\" id=\"70\" Color=\"Black\" /><TextFormat type=\"PerpetuumSoft.Framework.Text.TextF" +
            "ormat\" id=\"71\" UseCultureSettings=\"false\" FormatStyle=\"Number\" UseGroupSeparator" +
            "=\"true\" DecimalPlaces=\"0\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFil" +
            "l\" id=\"72\" /></Item></Elements><Values type=\"PerpetuumSoft.Charts.SeriesValueCol" +
            "lection\" id=\"73\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"74" +
            "\" Color=\"Maroon\" /></Item><Item type=\"PerpetuumSoft.Instrumentation.Model.Label\"" +
            " id=\"75\" Text=\"Quantidade dias consumir estoque\" Size=\"900;50\" Style=\"Default\" T" +
            "extAlign=\"TopLeft\" Center=\"550;250\" Name=\"Rótulo1\"><Stroke type=\"PerpetuumSoft.F" +
            "ramework.Drawing.EmptyStroke\" id=\"76\" /><Expressions type=\"PerpetuumSoft.Instrum" +
            "entation.Model.ExpressionBindingCollection\" id=\"77\" /><Fill type=\"PerpetuumSoft." +
            "Framework.Drawing.SolidFill\" id=\"78\" Color=\"Blue\" /></Item><Item type=\"Perpetuum" +
            "Soft.Instrumentation.Model.Label\" id=\"79\" Text=\"Estoque em Litros\" Size=\"900;50\"" +
            " Style=\"Default\" TextAlign=\"TopLeft\" Center=\"550;200\" Name=\"Rótulo2\"><Stroke typ" +
            "e=\"PerpetuumSoft.Framework.Drawing.EmptyStroke\" id=\"80\" /><Expressions type=\"Per" +
            "petuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"81\" /><Fill ty" +
            "pe=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"82\" Color=\"Black\" /></Item></" +
            "Elements></Item></Elements><Styles type=\"PerpetuumSoft.Instrumentation.Styles.St" +
            "yleCollection\" id=\"83\"><Item type=\"PerpetuumSoft.Instrumentation.Styles.Style\" i" +
            "d=\"84\" Name=\"Default\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke" +
            "\" id=\"85\" Width=\"1\" /><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor" +
            "\" id=\"86\" FamilyName=\"Microsoft Sans Serif\" /></Item><Item type=\"PerpetuumSoft.I" +
            "nstrumentation.Styles.Style\" id=\"87\" Name=\"Series1\"><Fill type=\"PerpetuumSoft.Fr" +
            "amework.Drawing.LinearGradientFill\" id=\"88\" StartColor=\"186, 250, 255\" EndColor=" +
            "\"121, 217, 254\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id" +
            "=\"89\" Width=\"5\" Color=\"213, 219, 226\" /></Item></Styles></root>")]
        public string LAYOUT_ESTOQUECOMB {
            get {
                return ((string)(this["LAYOUT_ESTOQUECOMB"]));
            }
            set {
                this["LAYOUT_ESTOQUECOMB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Charts.Chart\" id=\"1\" version=\"2\" Size=\"1409.375;950\" GridStep=\"50\" ShowGrid=\"fal" +
            "se\" Name=\"Chart\" MeasureUnit=\"Pixel\"><Parameters type=\"PerpetuumSoft.Instrumenta" +
            "tion.Model.ParameterCollection\" id=\"2\" /><Expressions type=\"PerpetuumSoft.Instru" +
            "mentation.Model.ExpressionBindingCollection\" id=\"3\" /><Bevel type=\"PerpetuumSoft" +
            ".Instrumentation.Model.StandardBevel\" id=\"4\" DownOffset=\"0\" CornerRadius=\"20\" Up" +
            "Offset=\"0\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"5\" Wi" +
            "dth=\"5\" Color=\"DarkGray\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.LinearGra" +
            "dientFill\" id=\"6\" Angle=\"270\" StartColor=\"213, 219, 226\" /><BevelShadow type=\"Pe" +
            "rpetuumSoft.Framework.Drawing.Shadow\" id=\"7\" DY=\"25\" DX=\"25\"><Fill type=\"Perpetu" +
            "umSoft.Framework.Drawing.LinearGradientFill\" id=\"8\" StartColor=\"Silver\" EndColor" +
            "=\"223, 223, 223\" /></BevelShadow></Bevel><Elements type=\"PerpetuumSoft.Instrumen" +
            "tation.Model.ElementCollection\" id=\"9\"><Item type=\"PerpetuumSoft.Charts.ChartAre" +
            "a\" id=\"10\" Size=\"1364.375;905\" Margins=\"0; 0; 0; 0\" Dock=\"Client\" Center=\"692.18" +
            "75;462.5\" PrimaryValueAxis=\"11\" Name=\"ChartArea1\"><Palette type=\"PerpetuumSoft.C" +
            "harts.PaletteRainbow\" id=\"12\" /><Expressions type=\"PerpetuumSoft.Instrumentation" +
            ".Model.ExpressionBindingCollection\" id=\"13\" /><Elements type=\"PerpetuumSoft.Inst" +
            "rumentation.Model.ElementCollection\" id=\"14\"><Item type=\"PerpetuumSoft.Charts.Ax" +
            "is\" id=\"15\" IsDiscrete=\"true\" Name=\"AxisX\"><Arrow type=\"PerpetuumSoft.Charts.Sha" +
            "rpAngleAxisArrow\" id=\"16\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.Simple" +
            "Stroke\" id=\"17\" Width=\"1\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Mod" +
            "el.ExpressionBindingCollection\" id=\"18\" /><Elements type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.ElementCollection\" id=\"19\" /></Item><Item type=\"PerpetuumSoft.Char" +
            "ts.Axis\" id=\"11\" Direction=\"Y\" MaxValue=\"110%\" Margins=\"0; 0; 312.5; 0\" Name=\"Ax" +
            "isY\" MinValue=\"0\"><Arrow type=\"PerpetuumSoft.Charts.SharpAngleAxisArrow\" id=\"20\"" +
            " /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"21\" Width=\"1\"" +
            " /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingColle" +
            "ction\" id=\"22\" /><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementColl" +
            "ection\" id=\"23\" /></Item><Item type=\"PerpetuumSoft.Charts.Title\" id=\"24\" TextAng" +
            "le=\"0\" Text=\"Saldo Caixa Operacional (R$)\" Size=\"1364.375;132.6568603515625\" Doc" +
            "kingStyle=\"Outside\" DockingType=\"Top\" Alignment=\"Center\" Center=\"692.1875;76.328" +
            "43017578125\" Padding=\"93.75; 0; 0; 0\" Name=\"Title1\"><Font type=\"PerpetuumSoft.Fr" +
            "amework.Drawing.FontDescriptor\" id=\"25\" FamilyName=\"Microsoft Sans Serif\" Size=\"" +
            "8.25\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"On\" Bold=\"On\" /><Expressions type=" +
            "\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"26\" /><Tex" +
            "tFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"27\" Color=\"Blue\" /><F" +
            "ill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"28\" /></Item><Item type" +
            "=\"PerpetuumSoft.Charts.Series\" id=\"29\" SortingType=\"Ascending\" DataSource=\"Caixa" +
            "Op\" AutoArgument=\"false\" Caption=\"\" Name=\"Série1\"><View type=\"PerpetuumSoft.Char" +
            "ts.PieSeriesView\" id=\"30\" InternalRadius=\"0\" StartAngle=\"0\" /><Expressions type=" +
            "\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"31\" /><Bin" +
            "dings type=\"PerpetuumSoft.Charts.SeriesBindingCollection\" id=\"32\"><Item type=\"Pe" +
            "rpetuumSoft.Charts.SeriesBinding\" id=\"33\" SeriesValueName=\"Value\" PropertyName=\"" +
            "vl_caixa\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"34\" SeriesValueN" +
            "ame=\"Argument\" PropertyName=\"trim (ds_portador)\" /><Item type=\"PerpetuumSoft.Cha" +
            "rts.SeriesBinding\" id=\"35\" SeriesValueName=\"UserData\" PropertyName=\"ds_portador\"" +
            " /></Bindings><Elements type=\"PerpetuumSoft.Instrumentation.Model.ElementCollect" +
            "ion\" id=\"36\"><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"37\" Distance=\"10\"" +
            " Name=\"Rótulos de Valor.1\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescr" +
            "iptor\" id=\"38\" FamilyName=\"Microsoft Sans Serif\" Size=\"9.75\" Underline=\"Off\" Str" +
            "ikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.ExpressionBindingCollection\" id=\"39\" /><TextFill type=\"PerpetuumSo" +
            "ft.Framework.Drawing.SolidFill\" id=\"40\" Color=\"Blue\" /><TextFormat type=\"Perpetu" +
            "umSoft.Framework.Text.TextFormat\" id=\"41\" UseCultureSettings=\"true\" FormatStyle=" +
            "\"Currency\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\" /><Fill type=\"PerpetuumSof" +
            "t.Framework.Drawing.EmptyFill\" id=\"42\" /></Item><Item type=\"PerpetuumSoft.Charts" +
            ".ValueLabels\" id=\"43\" Formula=\"trim (UserData)\" Distance=\"10\" Position=\"Center\" " +
            "Name=\"Rótulos de Valor.2\"><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescri" +
            "ptor\" id=\"44\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Underline=\"Off\" Stri" +
            "keout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"PerpetuumSoft.Instrumen" +
            "tation.Model.ExpressionBindingCollection\" id=\"45\" /><TextFill type=\"PerpetuumSof" +
            "t.Framework.Drawing.SolidFill\" id=\"46\" Color=\"Black\" /><TextFormat type=\"Perpetu" +
            "umSoft.Framework.Text.TextFormat\" id=\"47\" UseCultureSettings=\"false\" FormatStyle" +
            "=\"Number\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\" /><Fill type=\"PerpetuumSoft" +
            ".Framework.Drawing.EmptyFill\" id=\"48\" /></Item></Elements><Values type=\"Perpetuu" +
            "mSoft.Charts.SeriesValueCollection\" id=\"49\" /><Fill type=\"PerpetuumSoft.Framewor" +
            "k.Drawing.LinearGradientFill\" id=\"50\" StartColor=\"170, 0, 128, 0\" EndColor=\"149," +
            " 173, 255, 47\" /></Item></Elements></Item></Elements><Styles type=\"PerpetuumSoft" +
            ".Instrumentation.Styles.StyleCollection\" id=\"51\"><Item type=\"PerpetuumSoft.Instr" +
            "umentation.Styles.Style\" id=\"52\" Name=\"Default\"><Stroke type=\"PerpetuumSoft.Fram" +
            "ework.Drawing.SimpleStroke\" id=\"53\" Width=\"1\" /><Font type=\"PerpetuumSoft.Framew" +
            "ork.Drawing.FontDescriptor\" id=\"54\" FamilyName=\"Microsoft Sans Serif\" /></Item><" +
            "Item type=\"PerpetuumSoft.Instrumentation.Styles.Style\" id=\"55\" Name=\"Series1\"><F" +
            "ill type=\"PerpetuumSoft.Framework.Drawing.LinearGradientFill\" id=\"56\" StartColor" +
            "=\"186, 250, 255\" EndColor=\"121, 217, 254\" /><Stroke type=\"PerpetuumSoft.Framewor" +
            "k.Drawing.SimpleStroke\" id=\"57\" Width=\"5\" Color=\"213, 219, 226\" /></Item></Style" +
            "s></root>")]
        public string LAYOUT_CAIXAOP {
            get {
                return ((string)(this["LAYOUT_CAIXAOP"]));
            }
            set {
                this["LAYOUT_CAIXAOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Charts.Chart\" id=\"1\" version=\"2\" Size=\"1243.75;709.375\" GridStep=\"50\" ShowGrid=\"" +
            "false\" Name=\"Chart\" MeasureUnit=\"Pixel\"><Parameters type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.ParameterCollection\" id=\"2\" /><Expressions type=\"PerpetuumSoft.Ins" +
            "trumentation.Model.ExpressionBindingCollection\" id=\"3\" /><Bevel type=\"PerpetuumS" +
            "oft.Instrumentation.Model.StandardBevel\" id=\"4\" DownOffset=\"0\" CornerRadius=\"20\"" +
            " UpOffset=\"0\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"5\"" +
            " Width=\"5\" Color=\"DarkGray\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.Linear" +
            "GradientFill\" id=\"6\" Angle=\"270\" StartColor=\"213, 219, 226\" /><BevelShadow type=" +
            "\"PerpetuumSoft.Framework.Drawing.Shadow\" id=\"7\" DY=\"25\" DX=\"25\"><Fill type=\"Perp" +
            "etuumSoft.Framework.Drawing.LinearGradientFill\" id=\"8\" StartColor=\"Silver\" EndCo" +
            "lor=\"223, 223, 223\" /></BevelShadow></Bevel><Elements type=\"PerpetuumSoft.Instru" +
            "mentation.Model.ElementCollection\" id=\"9\"><Item type=\"PerpetuumSoft.Charts.Chart" +
            "Area\" id=\"10\" Size=\"1198.75;664.375\" Margins=\"0; 0; 0; 0\" Dock=\"Client\" Center=\"" +
            "609.375;342.1875\" PrimaryValueAxis=\"11\" Name=\"ChartArea1\"><Palette type=\"Perpetu" +
            "umSoft.Charts.PaletteRainbow\" id=\"12\" /><Expressions type=\"PerpetuumSoft.Instrum" +
            "entation.Model.ExpressionBindingCollection\" id=\"13\" /><Elements type=\"PerpetuumS" +
            "oft.Instrumentation.Model.ElementCollection\" id=\"14\"><Item type=\"PerpetuumSoft.C" +
            "harts.Axis\" id=\"15\" IsDiscrete=\"true\" Name=\"AxisX\"><Arrow type=\"PerpetuumSoft.Ch" +
            "arts.SharpAngleAxisArrow\" id=\"16\" /><Stroke type=\"PerpetuumSoft.Framework.Drawin" +
            "g.SimpleStroke\" id=\"17\" Width=\"1\" /><Expressions type=\"PerpetuumSoft.Instrumenta" +
            "tion.Model.ExpressionBindingCollection\" id=\"18\" /><Elements type=\"PerpetuumSoft." +
            "Instrumentation.Model.ElementCollection\" id=\"19\" /></Item><Item type=\"PerpetuumS" +
            "oft.Charts.Axis\" id=\"11\" Direction=\"Y\" MaxValue=\"110%\" Margins=\"0; 0; 312.5; 0\" " +
            "Name=\"AxisY\" MinValue=\"0\"><Arrow type=\"PerpetuumSoft.Charts.SharpAngleAxisArrow\"" +
            " id=\"20\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"21\" W" +
            "idth=\"1\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBind" +
            "ingCollection\" id=\"22\" /><Elements type=\"PerpetuumSoft.Instrumentation.Model.Ele" +
            "mentCollection\" id=\"23\" /></Item><Item type=\"PerpetuumSoft.Charts.Title\" id=\"24\"" +
            " TextAngle=\"0\" Text=\"Contas Receber\" Size=\"1198.75;132.6568603515625\" DockingSty" +
            "le=\"Outside\" DockingType=\"Top\" Alignment=\"Center\" Center=\"609.375;76.32843017578" +
            "125\" Padding=\"93.75; 0; 0; 0\" Name=\"Title1\"><Font type=\"PerpetuumSoft.Framework." +
            "Drawing.FontDescriptor\" id=\"25\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Un" +
            "derline=\"Off\" Strikeout=\"Off\" Italic=\"On\" Bold=\"On\" /><Expressions type=\"Perpetu" +
            "umSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"26\" /><TextFill ty" +
            "pe=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"27\" Color=\"Blue\" /><Fill type" +
            "=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"28\" /></Item><Item type=\"Perpet" +
            "uumSoft.Charts.Series\" id=\"29\" SeriesSortingType=\"Ascending\" DataSource=\"ContasR" +
            "ec\" AutoArgument=\"false\" Caption=\"\" Name=\"Série1\"><View type=\"PerpetuumSoft.Char" +
            "ts.BarSeriesView\" id=\"30\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Mod" +
            "el.ExpressionBindingCollection\" id=\"31\" /><Bindings type=\"PerpetuumSoft.Charts.S" +
            "eriesBindingCollection\" id=\"32\"><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" " +
            "id=\"33\" SeriesValueName=\"Value\" PropertyName=\"Valor\" /><Item type=\"PerpetuumSoft" +
            ".Charts.SeriesBinding\" id=\"34\" SeriesValueName=\"Argument\" PropertyName=\"Ds_label" +
            "\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"35\" SeriesValueName=\"Use" +
            "rData\" PropertyName=\"Ds_label\" /></Bindings><Elements type=\"PerpetuumSoft.Instru" +
            "mentation.Model.ElementCollection\" id=\"36\"><Item type=\"PerpetuumSoft.Charts.Valu" +
            "eLabels\" id=\"37\" Distance=\"10\" Name=\"Rótulos de Valor.1\"><Font type=\"PerpetuumSo" +
            "ft.Framework.Drawing.FontDescriptor\" id=\"38\" FamilyName=\"Microsoft Sans Serif\" S" +
            "ize=\"9.75\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expression" +
            "s type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"39\"" +
            " /><TextFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"40\" Color=\"Blu" +
            "e\" /><TextFormat type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"41\" UseCultu" +
            "reSettings=\"true\" FormatStyle=\"Currency\" UseGroupSeparator=\"true\" DecimalPlaces=" +
            "\"0\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"42\" /></Item><I" +
            "tem type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"43\" Formula=\"UserData\" Distance=" +
            "\"10\" Position=\"Center\" Name=\"Rótulos de Valor.2\"><Font type=\"PerpetuumSoft.Frame" +
            "work.Drawing.FontDescriptor\" id=\"44\" FamilyName=\"Microsoft Sans Serif\" Size=\"9.7" +
            "5\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions type=\"" +
            "PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"45\" /><Text" +
            "Fill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"46\" Color=\"Blue\" /><Te" +
            "xtFormat type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"47\" UseCultureSettin" +
            "gs=\"true\" FormatStyle=\"Currency\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\" /><F" +
            "ill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"48\" /></Item></Elements" +
            "><Values type=\"PerpetuumSoft.Charts.SeriesValueCollection\" id=\"49\" /><Fill type=" +
            "\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"50\" Color=\"Yellow\" /></Item></El" +
            "ements></Item></Elements><Styles type=\"PerpetuumSoft.Instrumentation.Styles.Styl" +
            "eCollection\" id=\"51\"><Item type=\"PerpetuumSoft.Instrumentation.Styles.Style\" id=" +
            "\"52\" Name=\"Default\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" " +
            "id=\"53\" Width=\"1\" /><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescriptor\" " +
            "id=\"54\" FamilyName=\"Microsoft Sans Serif\" /></Item><Item type=\"PerpetuumSoft.Ins" +
            "trumentation.Styles.Style\" id=\"55\" Name=\"Series1\"><Fill type=\"PerpetuumSoft.Fram" +
            "ework.Drawing.LinearGradientFill\" id=\"56\" StartColor=\"186, 250, 255\" EndColor=\"1" +
            "21, 217, 254\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"" +
            "57\" Width=\"5\" Color=\"213, 219, 226\" /></Item></Styles></root>")]
        public string LAYOUT_CONTASREC {
            get {
                return ((string)(this["LAYOUT_CONTASREC"]));
            }
            set {
                this["LAYOUT_CONTASREC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><root type=\"PerpetuumSoft." +
            "Charts.Chart\" id=\"1\" version=\"2\" Size=\"1243.75;709.375\" GridStep=\"50\" ShowGrid=\"" +
            "false\" Name=\"Chart\" MeasureUnit=\"Pixel\"><Parameters type=\"PerpetuumSoft.Instrume" +
            "ntation.Model.ParameterCollection\" id=\"2\" /><Expressions type=\"PerpetuumSoft.Ins" +
            "trumentation.Model.ExpressionBindingCollection\" id=\"3\" /><Bevel type=\"PerpetuumS" +
            "oft.Instrumentation.Model.StandardBevel\" id=\"4\" DownOffset=\"0\" CornerRadius=\"20\"" +
            " UpOffset=\"0\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"5\"" +
            " Width=\"5\" Color=\"DarkGray\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.Linear" +
            "GradientFill\" id=\"6\" Angle=\"270\" StartColor=\"213, 219, 226\" /><BevelShadow type=" +
            "\"PerpetuumSoft.Framework.Drawing.Shadow\" id=\"7\" DY=\"25\" DX=\"25\"><Fill type=\"Perp" +
            "etuumSoft.Framework.Drawing.LinearGradientFill\" id=\"8\" StartColor=\"Silver\" EndCo" +
            "lor=\"223, 223, 223\" /></BevelShadow></Bevel><Elements type=\"PerpetuumSoft.Instru" +
            "mentation.Model.ElementCollection\" id=\"9\"><Item type=\"PerpetuumSoft.Charts.Chart" +
            "Area\" id=\"10\" Size=\"1198.75;664.375\" Margins=\"0; 0; 0; 0\" Dock=\"Client\" Center=\"" +
            "609.375;342.1875\" PrimaryValueAxis=\"11\" Name=\"ChartArea1\"><Palette type=\"Perpetu" +
            "umSoft.Charts.PaletteRainbow\" id=\"12\" /><Expressions type=\"PerpetuumSoft.Instrum" +
            "entation.Model.ExpressionBindingCollection\" id=\"13\" /><Elements type=\"PerpetuumS" +
            "oft.Instrumentation.Model.ElementCollection\" id=\"14\"><Item type=\"PerpetuumSoft.C" +
            "harts.Axis\" id=\"15\" IsDiscrete=\"true\" Name=\"AxisX\"><Arrow type=\"PerpetuumSoft.Ch" +
            "arts.SharpAngleAxisArrow\" id=\"16\" /><Stroke type=\"PerpetuumSoft.Framework.Drawin" +
            "g.SimpleStroke\" id=\"17\" Width=\"1\" /><Expressions type=\"PerpetuumSoft.Instrumenta" +
            "tion.Model.ExpressionBindingCollection\" id=\"18\" /><Elements type=\"PerpetuumSoft." +
            "Instrumentation.Model.ElementCollection\" id=\"19\" /></Item><Item type=\"PerpetuumS" +
            "oft.Charts.Axis\" id=\"11\" Direction=\"Y\" MaxValue=\"110%\" Margins=\"0; 0; 312.5; 0\" " +
            "Name=\"AxisY\" MinValue=\"0\"><Arrow type=\"PerpetuumSoft.Charts.SharpAngleAxisArrow\"" +
            " id=\"20\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\" id=\"21\" W" +
            "idth=\"1\" /><Expressions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBind" +
            "ingCollection\" id=\"22\" /><Elements type=\"PerpetuumSoft.Instrumentation.Model.Ele" +
            "mentCollection\" id=\"23\" /></Item><Item type=\"PerpetuumSoft.Charts.Title\" id=\"24\"" +
            " TextAngle=\"0\" Text=\"Contas Pagar\" Size=\"1198.75;132.6568603515625\" DockingStyle" +
            "=\"Outside\" DockingType=\"Top\" Alignment=\"Center\" Center=\"609.375;76.3284301757812" +
            "5\" Padding=\"93.75; 0; 0; 0\" Name=\"Title1\"><Font type=\"PerpetuumSoft.Framework.Dr" +
            "awing.FontDescriptor\" id=\"25\" FamilyName=\"Microsoft Sans Serif\" Size=\"8.25\" Unde" +
            "rline=\"Off\" Strikeout=\"Off\" Italic=\"On\" Bold=\"On\" /><Expressions type=\"Perpetuum" +
            "Soft.Instrumentation.Model.ExpressionBindingCollection\" id=\"26\" /><TextFill type" +
            "=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"27\" Color=\"Blue\" /><Fill type=\"" +
            "PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"28\" /></Item><Item type=\"Perpetuu" +
            "mSoft.Charts.Series\" id=\"29\" SeriesSortingType=\"Ascending\" DataSource=\"ContasPag" +
            "\" AutoArgument=\"false\" Caption=\"Receber\" Name=\"Série1\"><View type=\"PerpetuumSoft" +
            ".Charts.BarSeriesView\" id=\"30\" /><Expressions type=\"PerpetuumSoft.Instrumentatio" +
            "n.Model.ExpressionBindingCollection\" id=\"31\" /><Bindings type=\"PerpetuumSoft.Cha" +
            "rts.SeriesBindingCollection\" id=\"32\"><Item type=\"PerpetuumSoft.Charts.SeriesBind" +
            "ing\" id=\"33\" SeriesValueName=\"Value\" PropertyName=\"Valor\" /><Item type=\"Perpetuu" +
            "mSoft.Charts.SeriesBinding\" id=\"34\" SeriesValueName=\"Argument\" PropertyName=\"Ds_" +
            "label\" /><Item type=\"PerpetuumSoft.Charts.SeriesBinding\" id=\"35\" SeriesValueName" +
            "=\"UserData\" PropertyName=\"Ds_label\" /></Bindings><Elements type=\"PerpetuumSoft.I" +
            "nstrumentation.Model.ElementCollection\" id=\"36\"><Item type=\"PerpetuumSoft.Charts" +
            ".ValueLabels\" id=\"37\" Distance=\"10\" Name=\"Rótulos de Valor.1\"><Font type=\"Perpet" +
            "uumSoft.Framework.Drawing.FontDescriptor\" id=\"38\" FamilyName=\"Microsoft Sans Ser" +
            "if\" Size=\"9.75\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expre" +
            "ssions type=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id" +
            "=\"39\" /><TextFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"40\" Color" +
            "=\"Blue\" /><TextFormat type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"41\" Use" +
            "CultureSettings=\"true\" FormatStyle=\"Currency\" UseGroupSeparator=\"true\" DecimalPl" +
            "aces=\"0\" /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"42\" /></It" +
            "em><Item type=\"PerpetuumSoft.Charts.ValueLabels\" id=\"43\" Formula=\"UserData\" Dist" +
            "ance=\"10\" Position=\"Center\" Name=\"Rótulos de Valor.2\"><Font type=\"PerpetuumSoft." +
            "Framework.Drawing.FontDescriptor\" id=\"44\" FamilyName=\"Microsoft Sans Serif\" Size" +
            "=\"9.75\" Underline=\"Off\" Strikeout=\"Off\" Italic=\"Off\" Bold=\"Off\" /><Expressions t" +
            "ype=\"PerpetuumSoft.Instrumentation.Model.ExpressionBindingCollection\" id=\"45\" />" +
            "<TextFill type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"46\" Color=\"Blue\" " +
            "/><TextFormat type=\"PerpetuumSoft.Framework.Text.TextFormat\" id=\"47\" UseCultureS" +
            "ettings=\"true\" FormatStyle=\"Currency\" UseGroupSeparator=\"true\" DecimalPlaces=\"0\"" +
            " /><Fill type=\"PerpetuumSoft.Framework.Drawing.EmptyFill\" id=\"48\" /></Item></Ele" +
            "ments><Values type=\"PerpetuumSoft.Charts.SeriesValueCollection\" id=\"49\" /><Fill " +
            "type=\"PerpetuumSoft.Framework.Drawing.SolidFill\" id=\"50\" Color=\"Yellow\" /></Item" +
            "></Elements></Item></Elements><Styles type=\"PerpetuumSoft.Instrumentation.Styles" +
            ".StyleCollection\" id=\"51\"><Item type=\"PerpetuumSoft.Instrumentation.Styles.Style" +
            "\" id=\"52\" Name=\"Default\"><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStr" +
            "oke\" id=\"53\" Width=\"1\" /><Font type=\"PerpetuumSoft.Framework.Drawing.FontDescrip" +
            "tor\" id=\"54\" FamilyName=\"Microsoft Sans Serif\" /></Item><Item type=\"PerpetuumSof" +
            "t.Instrumentation.Styles.Style\" id=\"55\" Name=\"Series1\"><Fill type=\"PerpetuumSoft" +
            ".Framework.Drawing.LinearGradientFill\" id=\"56\" StartColor=\"186, 250, 255\" EndCol" +
            "or=\"121, 217, 254\" /><Stroke type=\"PerpetuumSoft.Framework.Drawing.SimpleStroke\"" +
            " id=\"57\" Width=\"5\" Color=\"213, 219, 226\" /></Item></Styles></root>")]
        public string LAYOUT_CONTASPAG {
            get {
                return ((string)(this["LAYOUT_CONTASPAG"]));
            }
            set {
                this["LAYOUT_CONTASPAG"] = value;
            }
        }
    }
}
